The following new files/directories were created:
<Test Directory>
----texttesttmp
--------console.env.queuesystem.06Mar152402.10280
------------slavelogs
----------------Test-Test2-TDAT.env.queuesystem.errors
----------------Test-Test2-TDAT.env.queuesystem.log
------------tdat.env.queuesystem
----------------Test2
--------------------catalogue.tdat
--------------------errors.tdat
--------------------output.tdat
--------------------framework_tmp
------------------------catalogue.tdatcmp
------------------------catalogue.tdatorigcmp
------------------------errors.tdatcmp
------------------------errors.tdatorigcmp
------------------------output.tdatcmp
------------------------output.tdatorigcmp
