TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.sge.15Oct153005/texttest.sge/TestSelf/TestData/Console/CopyEnvironmentPath based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application TDAT, version env.queuesystem
Running TDAT.env.queuesystem test-suite TargetApp
  Running TDAT.env.queuesystem test-case Test2
Comparing differences for TDAT.env.queuesystem test-suite TargetApp
  Comparing differences for TDAT.env.queuesystem test-case Test2 (on catalogue.tdat,errors.tdat,output.tdat)
