TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/TestSelf/TestData/Console/CopyEnvironmentPath based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/TestSelf/TestData/Console/CopyEnvironmentPath/logging
Using Application TDAT, version env.queuesystem
Running TDAT.env.queuesystem test-suite TargetApp
  Running TDAT.env.queuesystem test-case Test2
Comparing differences for TDAT.env.queuesystem test-suite TargetApp
  Comparing differences for TDAT.env.queuesystem test-case Test2 (on catalogue.tdat,errors.tdat,output.tdat)
