Using SGE queues for Application HELLO, version multiresource, checkout /tmp/geoff/texttest.25May172628.67389/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ResourceOrderChanges/TargetApp/
Q: Submitting HELLO.multiresource test-case Test to default SGE queue
S: HELLO.multiresource test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Approve Version multiresource(1), Approve(a) or continue(any other key)?
S: HELLO.multiresource test-case Test succeeded on centreville.carmen.se
