TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff31Aug141023/QueueSystems/GUI/SlaveCrash based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badslave, checkout /users/geoff/texttesttmp/texttest.sgegeoff31Aug141023/QueueSystems/GUI/SlaveCrash/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Reading slave results for SLEEP test-case Basic (unrunnable)
