Using SGE queues for Application HELLO, version changeenv, checkout /home/geoff/.texttest/tmp/dynamic_gui.1_from_03apr174421.64155/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ClearEnvironment/TargetApp/
Q: Submitting HELLO.changeenv test-case Test to default SGE queue
S: HELLO.changeenv test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Approve Version changeenv(1), Approve(a) or continue(any other key)?
S: HELLO.changeenv test-case Suite/Test succeeded on centreville.carmen.se
