TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.13Nov141742/texttest.lsf/QueueSystems/NormalOperation/Console/Batch2Tests based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default LSF queue
Q: Submitting SLEEP test-case Basic2 to default LSF queue
S: SLEEP test-case Basic succeeded on forestville
S: SLEEP test-case Basic2 FAILED on forestville : new results in errors,output
At 14:18 creating batch report for application SLEEP ...file written.
