TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.07Jun164202/QueueSystems/NormalOperation/Console/Batch2Tests based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  Submitting SLEEP test-case Basic2 to default SGE queue
  SLEEP test-case Basic2 FAILED on connellsville : new results in errors,output
  SLEEP test-case Basic  succeeded on graceville
At 16:42 creating batch report for application SLEEP ...file written.
