TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct134053/texttest.lsf/QueueSystems/NormalOperation/Console/Batch2Tests based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default LSF queue
Q: Submitting SLEEP test-case Basic2 to default LSF queue
S: SLEEP test-case Basic succeeded on quaqtaq
S: SLEEP test-case Basic2 FAILED on quaqtaq : new results in errors,output
At 13:40 creating batch report for application SLEEP ...file written.
