TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.sge/QueueSystems/NormalOperation/Console/Batch2Tests based on file at /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.sge/QueueSystems/NormalOperation/Console/Batch2Tests/logging
Using SGE queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default SGE queue
Q: Submitting SLEEP test-case Basic2 to default SGE queue
S: SLEEP test-case Basic2 FAILED on sunriver : new results in errors,output
S: SLEEP test-case Basic succeeded on sundance
At 15:20 creating batch report for application SLEEP ...
File written.
