TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.13Jun123443/QueueSystems/NormalOperation/Console/Batch2Tests based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP
Q: Submitting test Basic to default LSF queue
Q: Submitting test Basic2 to default LSF queue
S: Test Basic succeeded on quaqtaq
S: Test Basic2 FAILED on quaqtaq : new results in errors,output
At 12:35 creating batch report for application SLEEP ...file written.
