TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.30Nov175319/QueueSystems/NormalOperation/Console/Batch2Tests based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  Submitting SLEEP test-case Basic2 to default SGE queue
  SLEEP test-case Basic2 FAILED on smithville : new results in errors,output
  SLEEP test-case Basic  succeeded on granville
At 17:55 creating batch report for application SLEEP ...file written.
