TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Limits/Master/CpuLimit based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Limits/Master/CpuLimit/logging
Using SGE queues for Application SLEEP, version killing3.cpulimit
Q: Submitting SLEEP.killing3.cpulimit test-case Basic to default SGE queue
S: SLEEP.killing3.cpulimit test-case Basic were terminated before completion (CPULIMIT) on forestville : differences in output
At 15:40 creating batch report for application SLEEP ...file written.
