TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/Limits/Master/CpuLimit based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version killing3.cpulimit
Q: Submitting SLEEP.killing3.cpulimit test-case Basic to default SGE queue
S: SLEEP.killing3.cpulimit test-case Basic were terminated before completion (CPULIMIT) on forestville : differences in output
At 17:34 creating batch report for application SLEEP ...file written.
