TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.sge/QueueSystems/Limits/Master/CpuLimit based on file at /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.sge/QueueSystems/Limits/Master/CpuLimit/logging
Using SGE queues for Application SLEEP, version killing3.cpulimit
Q: Submitting SLEEP.killing3.cpulimit test-case Basic to default SGE queue
S: SLEEP.killing3.cpulimit test-case Basic were terminated before completion (CPULIMIT) on forestville : differences in output
At 15:20 creating batch report for application SLEEP ...
File written.
