<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/Performance/CheckExecHost/ShortMachineNames/texttesttmp/perf.resourcegeoff28Aug101851/Failures:$PATH' 'USECASE_RECORD_SCRIPT=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/Performance/CheckExecHost/ShortMachineNames/texttesttmp/perf.resourcegeoff28Aug101851/Failures/usecase.perf' 'USECASE_RECORD_STDIN=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/Performance/CheckExecHost/ShortMachineNames/texttesttmp/perf.resourcegeoff28Aug101851/Failures/input.perf' bhosts -w -R performance_resource
->OUT:HOST_NAME          STATUS          JL/U    MAX  NJOBS    RUN  SSUSP  USUSP    RSV 
perf_machine1 ok                 -      2      0      0      0      0      0
perf_machine2 ok                 -      2      0      0      0      0      0
bagotville    ok                 -      2      0      0      0      0      0
batesville    ok                 -      2      0      0      0      0      0
bellville     ok                 -      2      0      0      0      0      0
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/Performance/CheckExecHost/ShortMachineNames/texttesttmp/perf.resourcegeoff28Aug101851/Failures:$PATH' 'USECASE_RECORD_SCRIPT=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/Performance/CheckExecHost/ShortMachineNames/texttesttmp/perf.resourcegeoff28Aug101851/Failures/usecase.perf' 'USECASE_RECORD_STDIN=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/Performance/CheckExecHost/ShortMachineNames/texttesttmp/perf.resourcegeoff28Aug101851/Failures/input.perf' bjobs -m perf_machine1 -u all -w
->ERR:No unfinished job found on host/group <perf_machine1>
