TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff24Jan14:56:47/lsf/BatchTestNotInParent based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff24Jan14:56:47/lsf/BatchTestNotInParent/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic3 to default SGE queue
  Reading slave results for SLEEP test-case Basic3 (on errors.sleep,output.sleep)
  SLEEP test-case Basic3 on abbeville : new results in errors,output
At 14:57 creating batch report for application SLEEP ...done.
