TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff24Jan16:05:51/lsf/BadQueueCommandLine based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff24Jan16:05:51/lsf/BadQueueCommandLine/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to SGE queue non_existent
  Submitting SLEEP test-case Basic2 to SGE queue non_existent
  SLEEP test-case Basic  not compared:  Failed to submit to SGE (Unable to run job: Job was rejected because job requests unknown queue "non_existent".)
  SLEEP test-case Basic2 not compared:  Failed to submit to SGE (Unable to run job: Job was rejected because job requests unknown queue "non_existent".)
