TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff12Sep172415/QueueSystems/Console/RunLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing3, checkout /users/geoff/texttesttmp/texttest.sgegeoff12Sep172415/QueueSystems/Console/RunLimit/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Reading slave results for SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
  SLEEP test-case Basic were terminated before completion (RUNLIMIT) on brockville :
At 17:24 creating batch report for application SLEEP ...file written
