TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff11Nov115909/QueueSystems/Console/RunLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing3, checkout /users/geoff/texttesttmp/texttest.sgegeoff11Nov115909/QueueSystems/Console/RunLimit/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Evaluating SLEEP test-case Basic (on errors.sleep,output.sleep)
  SLEEP test-case Basic were terminated before completion (RUNLIMIT) on woodville : differences in output
At 11:59 creating batch report for application SLEEP ...file written
