TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Performance/Miscellaneous/ExtractPerfResource based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Performance/Miscellaneous/ExtractPerfResource/logging
Using Application PERF, version resource
Extracting standard performance for PERF.resource test-suite TargetApp
  Extracting standard performance for PERF.resource test-case Failures
