TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff18Aug142113/QueueSystems/Console/Slave/PerformanceChecking/ExtractPerfResource based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application PERF, version resource
Extracting standard performance for PERF test-suite TargetApp
  Extracting standard performance for PERF test-case Failures
