geoff@localhost
unrunnable=1
060703 SLEEP killing : 1 tests : 1 unrunnable

Summary of all Unsuccessful tests follows...
---------------------------------------------------------------------------------
The following tests could not be run : 
In SLEEP test-suite TargetApp:
  - SLEEP test-case Basic : SGE/system error


Details of all Unsuccessful tests follows...
---------------------------------------------------------------------------------

Detailed information for the tests that could not be run follows...
--------------------------------------------------------
TEST could not be run : SLEEP test-case Basic (under Basic)
SGE/system error
Full accounting info from SGE follows:
This job ran several days ago!

