#!/usr/bin/env python

import sys, os
machine = sys.argv[1]
if machine.find("machine1") != -1:
    sys.stderr.write(machine + ": Unknown host\n")
else:
    os.environ["TEXTTEST_FAKE_MACHINE"] = machine
    command = sys.argv[2]
    os.system(command)
