<-SRV:TextTest slave server started on 10.67.7.142:37103
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobAppearsAfterDelay/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobAppearsAfterDelay/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobAppearsAfterDelay/texttesttmp/sleep.killing.20Dec105127.17863 -servaddr 10.67.7.142:59726 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job 1 does not exist
<-CMD:qacct -j 1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobAppearsAfterDelay/sge/default/common/accounting.0
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobAppearsAfterDelay/sge/default/common/accounting.1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1
->OUT:Now we've found the information!
