universe = vanilla
getenv = true
executable = /home/geoff/code/texttest/bin/texttest.py
arguments = -d /home/geoff/.texttest/tmp/texttest.condor.29Aug215246.24963/texttest.condor/QueueSystems/NormalOperation/Console/Batch2Tests/TargetApp -a sleep -l -tp Basic2 -slave /home/geoff/.texttest/tmp/texttest.condor.29Aug215246.24963/texttest.condor/QueueSystems/NormalOperation/Console/Batch2Tests/texttesttmp/local.29Aug215247.24966 -servaddr 127.0.0.1:37313 -b local
requirements = 
output = Test-Basic2-SLEEP.out
error = Test-Basic2-SLEEP.errors
log = Test-Basic2-SLEEP.log
queue
