<-CMD:env 'TEXTTEST_HOME=/users/geoff/texttesttmp/texttest.sge.08May094100/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/TargetApp' 'TEXTTEST_TMP=/users/geoff/texttesttmp/texttest.sge.08May094100/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/texttesttmp' time -p sh -c "python /users/geoff/texttesttmp/texttest.sge.08May094100/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/TargetApp/writeperfnumbers.py  < /users/geoff/texttesttmp/texttest.sge.08May094100/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/TargetApp/Failures/input.perf > /users/geoff/texttesttmp/texttest.sge.08May094100/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/texttesttmp/perf.08May094344/Failures/output.perf 2> /users/geoff/texttesttmp/texttest.sge.08May094100/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/texttesttmp/perf.08May094344/Failures/errors.perf"
->ERR:real 6.02
user 5.01
sys 2.00
<-CMD:qselect -l performance_resource
->OUT:idle@perf_machine1.carmen.se
idle@perf_machine2.carmen.se
idle@bagotville.carmen.se
idle@batesville.carmen.se
idle@bellville.carmen.se
login@perf_machine1.carmen.se
login@perf_machine2.carmen.se
login@bagotville.carmen.se
login@batesville.carmen.se
login@bellville.carmen.se
waiting@perf_machine1.carmen.se
waiting@perf_machine2.carmen.se
waiting@bagotville.carmen.se
waiting@batesville.carmen.se
waiting@bellville.carmen.se
build@perf_machine1.carmen.se
build@perf_machine2.carmen.se
build@bagotville.carmen.se
build@batesville.carmen.se
build@bellville.carmen.se
short@perf_machine1.carmen.se
short@perf_machine2.carmen.se
short@bagotville.carmen.se
short@batesville.carmen.se
short@bellville.carmen.se
normal@perf_machine1.carmen.se
normal@perf_machine2.carmen.se
normal@bagotville.carmen.se
normal@batesville.carmen.se
normal@bellville.carmen.se
<-CMD:qstat -r -s r -l hostname=perf_machine1
