<-CMD:env 'TEXTTEST_HOME=/users/geoff/texttesttmp/texttest.sge.04Jan174730/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/TargetApp' 'TEXTTEST_TMP=/users/geoff/texttesttmp/texttest.sge.04Jan174730/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/texttesttmp' time -p sh /users/geoff/texttesttmp/texttest.sge.04Jan174730/QueueSystems/Performance/Miscellaneous/MeasureCpuResource/texttesttmp/perf.04Jan174735/Failures/framework_tmp/cmd
->ERR:real 6.02
user 5.01
sys 2.00
<-CMD:bhosts -w -R performance_resource
->OUT:HOST_NAME          STATUS          JL/U    MAX  NJOBS    RUN  SSUSP  USUSP    RSV 
perf_machine1.carmen.se ok                 -      2      0      0      0      0      0
perf_machine2.carmen.se ok                 -      2      0      0      0      0      0
bagotville.carmen.se    ok                 -      2      0      0      0      0      0
batesville.carmen.se    ok                 -      2      0      0      0      0      0
bellville.carmen.se     ok                 -      2      0      0      0      0      0
<-CMD:bjobs -m perf_machine1 -u all -w
->ERR:No unfinished job found on host/group <perf_machine1>
