TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff01Jun140334/QueueSystems/Console/NightjobTerminate based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff01Jun140334/QueueSystems/Console/NightjobTerminate/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Received signal for termination in 10 minutes, killing all remaining jobs
  Killing SLEEP test-case Basic (Emergency finish of job 325136)
  SLEEP test-case Basic not compared
At 14:03 creating batch report for application SLEEP ...file written
