TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff05Sep143705/QueueSystems/Console/NightjobTerminate based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff05Sep143705/QueueSystems/Console/NightjobTerminate/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Received signal for termination, killing all remaining tests...
  Cancelling SLEEP test-case Basic in SGE (Emergency finish of job 1065362)
  Reading slave results for SLEEP test-case Basic (killed)
  SLEEP test-case Basic not compared:  Test killed explicitly at 14:37
At 14:37 creating batch report for application SLEEP ...file written
