TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/NightjobTerminate based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/NightjobTerminate/TargetApp/
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
  Cancelling SLEEP test-case Basic in SGE (job 2751939)
  SLEEP test-case Basic were terminated before completion (killed at 17:34) on cartierville : differences in output
At 17:34 creating batch report for application SLEEP ...file written
