TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff24Jan14:52:39/lsf/BadPerformanceMachine based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badperfmachine, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff24Jan14:52:39/lsf/BadPerformanceMachine/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  Submitting SLEEP test-case Basic2 to default SGE queue
  SLEEP test-case Basic  not compared:  Failed to submit to SGE (Unable to run job: can't resolve hostname "no_such_machine|no_such_machine2".)
  SLEEP test-case Basic2 not compared:  Failed to submit to SGE (Unable to run job: can't resolve hostname "no_such_machine|no_such_machine2".)
