<-SRV:TextTest slave server started on 10.67.7.114:36803
<-CMD:cd /nfs/vm/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/Console/PollJobLost/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/Console/PollJobLost/texttesttmp/grid_core_files/slave_start_errors.johgil exec $SHELL -c "exec /carm/proj/dave/workspace/johgil/texttest-tool/texttest/bin/texttest -d /carm/proj/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/Console/PollJobLost/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/Console/PollJobLost/texttesttmp/sleep.killing.29Sep135101.3200875 -servaddr 127.0.0.1:42461 -b short_local"
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
->CLI:6035
sleep.killing:Basic
(itexttestlib.default
Running
p1
(dp2
S'category'
p3
S'running'
p4
sS'freeText'
p5
S'Running on abbeville'
p6
sS'started'
p7
I1
sS'completed'
p8
I0
sS'briefText'
p9
S'RUN (abbeville)'
p10
sS'executionHosts'
p11
(lp12
S'abbeville'
p13
asS'observers'
p14
(lp15
sS'passSelf'
p16
I00
sS'lifecycleChange'
p17
S'start'
p18
sb.
<-CMD:qstat
<-CMD:qacct -j 1
->OUT:Some random accounting info
