Using LSF queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default LSF queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling SLEEP.killing test-case Basic in LSF (job 1)
S: SLEEP.killing test-case Basic not compared:
LSF job exited
---------- Full accounting info from LSF ----------
LSF lost job:1
Creating batch report for application SLEEP ...
File written.
