<-SRV:TextTest slave server started on 192.168.99.65:58803
<-CMD:cd /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappears/texttesttmp/sleep.killing.11Sep114050/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' bsub -J Test-Basic-SLEEP.killing -u nobody -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappears/TargetApp -a sleep -v killing -l -tp Basic -slave /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappears/texttesttmp/sleep.killing.11Sep114050 -servaddr 192.168.99.65:58799 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappears/slave"'
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:bjobs -a -l 1
->ERR:Job <1> is not found
