<-SRV:192.168.99.30:50585
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobDisappears/texttesttmp/sleep.killinggeoff28Aug101857/Basic:$PATH' 'USECASE_RECORD_SCRIPT=' 'USECASE_RECORD_STDIN=' 'USECASE_REPLAY_SCRIPT=' bsub -J Test-Basic-SLEEP.killing -u nobody -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest.py -d /users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobDisappears/TargetApp -a sleep -v killing -l  -tp Basic -slave /users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobDisappears/texttesttmp/sleep.killinggeoff28Aug101857 -servaddr 192.168.99.30:50583 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest -xw /users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobDisappears/slave"'
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobDisappears/texttesttmp/sleep.killinggeoff28Aug101857/Basic:$PATH' bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobDisappears/texttesttmp/sleep.killinggeoff28Aug101857/Basic:$PATH' bjobs -a -l 1
->ERR:Job <1> is not found
