<-SRV:TextTest slave server started on 10.67.7.36:38912
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.20876/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.20876/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.20876/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/texttesttmp/sleep.killing.20Dec105127.25855 -servaddr 10.67.7.36:34740 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job 1 does not exist
<-CMD:qacct -j 1
->OUT:Some random accounting info
