<-SRV:TextTest slave server started on 10.67.7.144:52326
<-CMD:cd /tmp/geoff/texttest.lsf.signals.27May152123.18002/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/texttesttmp/grid_core_files; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT bsub -J Test-Basic-SLEEP.killing -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.signals.27May152123.18002/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.lsf.signals.27May152123.18002/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/texttesttmp/sleep.killing.27May152125.20572 -servaddr 127.0.0.1:42379 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:bjobs -a -l 1
->OUT:Some random accounting info
