<-SRV:TextTest slave server started on 10.80.17.109:40009
<-CMD:cd /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/SlaveCrashNoReport/texttesttmp/sleep.killing.17Sep112811.2079 -servaddr 127.0.0.1:46690 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job 1 does not exist
<-CMD:qacct -j 1
->OUT:Some random accounting info
