TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/Limits/Master/RunLimit based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/Limits/Master/RunLimit/logging
Using LSF queues for Application SLEEP, version killing3
Q: Submitting SLEEP.killing3 test-case Basic to default LSF queue
S: SLEEP.killing3 test-case Basic were terminated before completion (RUNLIMIT) on forestville : differences in output
At 15:40 creating batch report for application SLEEP ...file written.
