TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.11Oct180920/QueueSystems/Limits/Master/RunLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing3
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Evaluating SLEEP test-case Basic (on errors.sleep,output.sleep)
  SLEEP test-case Basic were terminated before completion (RUNLIMIT) on circleville : differences in output
At 18:11 creating batch report for application SLEEP ...file written.
