TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.02Oct160717/texttest.sge/QueueSystems/Limits/Master/RunLimit based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version killing3
Q: Submitting SLEEP.killing3 test-case Basic to default SGE queue
S: SLEEP.killing3 test-case Basic were terminated before completion (RUNLIMIT) on abbeville : differences in output
At 16:08 creating batch report for application SLEEP ...file written.
