TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.lsf/QueueSystems/Limits/Master/RunLimit based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version killing3
Q: Submitting SLEEP.killing3 test-case Basic to default LSF queue
S: SLEEP.killing3 test-case Basic were terminated before completion (RUNLIMIT) on forestville : differences in output
At 17:34 creating batch report for application SLEEP ...file written.
