TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.13Jun115925/QueueSystems/Limits/Master/RunLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version killing3
Q: Submitting test Basic to default SGE queue
S: Test Basic were terminated before completion (RUNLIMIT) on abbeville : differences in output
At 11:59 creating batch report for application SLEEP ...file written.
