TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.13Jun134533/QueueSystems/Limits/Master/RunLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version killing3
Q: Submitting test Basic to default LSF queue
S: Test Basic were terminated before completion (RUNLIMIT) on forestville : differences in output
At 13:45 creating batch report for application SLEEP ...file written.
