#!/bin/sh
echo "JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME"
echo "1  $USER   EXIT  fake_machine_queue     fake_machine  fake_machine1.carmen.se:fake_machine2.carmen.se fake_name       Sep  7 15:37"
