# Unless otherwise stated, we use the LSF settings
base_version:lsf

extra_version:{CLEAR LIST}

# Fake queue system directory...
link_test_path:{CLEAR LIST}
link_test_path:qsub
link_test_path:sgehostfile
link_test_path:qdel
link_test_path:qacct
# For faking rave C-compilations
link_test_path:gcc32
link_test_path:gcc
# Test state repository
partial_copy_test_path:/carm/proj/texttest/selftest_data/TestStateRepository
