base_version:queuesystem

# Fake queue system directory...
link_test_path:qsub
link_test_path:qdel
link_test_path:sgehostfile

collect_traffic:qsub
collect_traffic:qdel
collect_traffic:qacct
collect_traffic:qselect
collect_traffic:qstat

[collect_traffic_environment]
qsub:USECASE_RECORD_SCRIPT
qsub:USECASE_REPLAY_SCRIPT
# Test environment variable, make sure it isn't set externally when it shouldn't be
qsub:TO_GREET

[test_data_environment]
sgehostfile:PE_HOSTFILE
