#!/usr/bin/env python

import sys, os
from getopt import getopt

output = """real 7.02
user 3.5
sys 1.5
"""

options, args = getopt(sys.argv[1:], "po:")
perfFile = dict(options).get("-o")
targetFile = open(perfFile, "w")
print "Writing to", perfFile, output
targetFile.write(output)
targetFile.close()
os.execvp(args[0], args)
