TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.04Jul143732/QueueSystems/SlaveReuse/Master/ForceReuse/ReuseOnlyBeyondCapacity based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /users/geoff/texttesttmp/texttest.sge.04Jul143732/QueueSystems/SlaveReuse/Master/ForceReuse/ReuseOnlyBeyondCapacity/TargetApp/
Q: Submitting test Test under TargetApp to default SGE queue
S: Test Test under TargetApp FAILED on forestville : differences in output
View details(v), Save(s) or continue(any other key)?
S: Test Test under Suite succeeded on forestville
