TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/ReuseOnlyBeyondCapacity based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/ReuseOnlyBeyondCapacity/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on forestville : differences in output
View details(v), Save(s) or continue(any other key)?
S: HELLO test-case Test succeeded on forestville
