TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff11Feb13:58:39/QueueSystems/Console/BadResourceUsage based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badresusage, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff11Feb13:58:39/QueueSystems/Console/BadResourceUsage/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  SLEEP test-case Basic not compared:  Failed to submit to SGE (Unable to run job: unknown resource "rusage[no_such_resource".)
