<-SRV:TextTest slave server started on 192.168.98.14:40168
<-CMD:cd /nfs/vm/texttest-tmp/geoff/dynamic_gui.15Aug140757.2977/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/JobAppearsAfterDelay/texttesttmp/sleep.killing.15Aug140759.2988/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -V -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors 'exec $SHELL -c "exec /carm/proj/texttest/release/current/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.15Aug140757.2977/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/JobAppearsAfterDelay/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.15Aug140757.2977/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/JobAppearsAfterDelay/texttesttmp/sleep.killing.15Aug140759.2988 -servaddr 192.168.98.14:40167 -b short_local"'
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job 1 does not exist
<-CMD:qacct -j 1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /carm/proj/texttest-tmp/geoff/dynamic_gui.15Aug140757.2977/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/JobAppearsAfterDelay/sge/default/common/accounting.0
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /carm/proj/texttest-tmp/geoff/dynamic_gui.15Aug140757.2977/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/JobAppearsAfterDelay/sge/default/common/accounting.1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1
->OUT:Now we've found the information!
