TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.04Jun112711/QueueSystems/Limits/Slave/KillTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version killing
Running SLEEP test-suite TargetApp
  Running SLEEP test-case Basic
Terminating testing due to external interruption (RUNLIMIT1)
Killing running test (process id 25263)
Comparing differences for SLEEP test-suite TargetApp
  Comparing differences for SLEEP test-case Basic (on errors.sleep,output.sleep)
  SLEEP test-case Basic were terminated before completion (killed at 11:30) on louisville : differences in output
