TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Limits/Slave/KillTest based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Limits/Slave/KillTest/logging
Using Application SLEEP, version killing
Running SLEEP.killing test-suite TargetApp
  Running SLEEP.killing test-case Basic
Terminating testing due to external interruption (RUNLIMIT2)
Killing running test (process id 18809)
Comparing differences for SLEEP.killing test-suite TargetApp
  Comparing differences for SLEEP.killing test-case Basic (on errors.sleep,output.sleep)
