<-SRV:TextTest slave server started on 10.0.2.100:57915
<-CMD:cd /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v STANDARD,DISPLAY -o /dev/null -e /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/grid_core_files/slave_start_errors.matlar exec $SHELL -c "exec /home/matlar/work/texttest-devel/local/texttest/bin/texttest -d /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/TargetApp -a sleep.killing -l -tp Basic -slave /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.22Jan143343.2126162 -servaddr 127.0.0.1:52877 -b short_local"
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
->FIL:sleep.killing.10Nov171707.26890
<-CMD:qstat
<-CMD:qacct -j 1
->OUT:Some random accounting info
