<-SRV:TextTest slave server started on 10.80.17.109:56470
<-CMD:cd /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.17Sep112807.1940 -servaddr 127.0.0.1:46141 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
->FIL:sleep.killing.10Nov171707.26890
<-CMD:qstat
<-CMD:qacct -j 1
->OUT:Some random accounting info
