<-SRV:TextTest slave server started on 10.67.7.146:41893
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105140.21208/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.20Dec105142.25803/slavelogs; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105140.21208/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105140.21208/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.20Dec105142.25803 -servaddr 10.67.7.146:52566 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
->FIL:sleep.killing.10Nov171707.26890
<-CMD:qstat
<-CMD:qacct -j 1
->OUT:Some random accounting info
