Using LSF queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default LSF queue
S: SLEEP.killing test-case Basic not compared:
LSF job exited
---------- Error messages written by LSF job ----------
Some Beautiful Error Message...
With Extra Nonsense
---------- Full accounting info from LSF ----------
Some random accounting info

Creating batch report for application SLEEP ...
File written.
