<-SRV:TextTest slave server started on 10.67.20.109:56593
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.14May160550.19888/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.14May160553.19897/slavelogs; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -V -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors "exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /carm/proj/texttest-tmp/geoff/texttest.14May160550.19888/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/TargetApp -a sleep.killing -l -tp 'Basic' -slave /carm/proj/texttest-tmp/geoff/texttest.14May160550.19888/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.14May160553.19897 -servaddr 10.67.20.109:49210 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qstat 
->OUT:job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
   8338 0.53687 build 13 x annao        r     03/26/2010 08:39:17 login@carlisle.got.jeppesensys     1
<-CMD:qacct -j 1
->OUT:Some random accounting info
