<-SRV:TextTest slave server started on 10.67.7.93:60796
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.16Nov151344.26643/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.16Nov151433.6288/slavelogs; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -V -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors "exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /carm/proj/texttest-tmp/geoff/texttest.16Nov151344.26643/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/TargetApp -a sleep.killing -l -tp 'Basic' -slave /carm/proj/texttest-tmp/geoff/texttest.16Nov151344.26643/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.16Nov151433.6288 -servaddr 10.67.7.93:33217 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qacct -j 1
->OUT:Some random accounting info
