TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/TestSelf/TestData/LinkedData/PartialCopyIgnoreCatalogues based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/TestSelf/TestData/LinkedData/PartialCopyIgnoreCatalogues/logging
Using SGE queues for Application TDAT, version queuesystem
Q: Submitting TDAT.queuesystem test-case Test1 to default SGE queue
S: TDAT.queuesystem test-case Test1 succeeded on statesville
