TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/TestSelf/TestData/UnixOnly/PartialCopyIgnoreCatalogues based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application TDAT, version queuesystem
Q: Submitting TDAT.queuesystem test-case Test1 to default SGE queue
S: TDAT.queuesystem test-case Test1 succeeded on statesville
