TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.27Jun120427/QueueSystems/ErrorHandling/Console/PreviousWriteDir based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version startdigit
Removing previous write directory /users/geoff/texttesttmp/texttest.lsf.27Jun120427/QueueSystems/ErrorHandling/Console/PreviousWriteDir/texttesttmp/sleep.startdigit.14Apr2007
Q: Submitting test 123Test to default LSF queue
S: Test 123Test FAILED on forestville : new results in errors,output
View details(v), Save Version startdigit(1), Save(s) or continue(any other key)?
