TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.13Nov141742/texttest.lsf/QueueSystems/ErrorHandling/Console/PreviousWriteDir based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Removing previous write directory /carm/proj/texttest/geoff/texttesttmp/texttest.13Nov141742/texttest.lsf/QueueSystems/ErrorHandling/Console/PreviousWriteDir/texttesttmp/console.startdigit.14Apr2007
Using LSF queues for Application SLEEP, version startdigit
Q: Submitting SLEEP.startdigit test-case 123Test to default LSF queue
S: SLEEP.startdigit test-case 123Test succeeded on forestville
