TextTest will write diagnostics in /nfs/vm/texttest-tmp/geoff/texttest.07Feb181234/texttest.sge/QueueSystems/ErrorHandling/Console/PreviousWriteDir based on file at /carm/proj/texttest-tmp/geoff/texttest.07Feb181234/texttest.sge/QueueSystems/ErrorHandling/Console/PreviousWriteDir/logging
Removing previous write directory /carm/proj/texttest-tmp/geoff/texttest.07Feb181234/texttest.sge/QueueSystems/ErrorHandling/Console/PreviousWriteDir/texttesttmp/console.startdigit.14Apr2007
Using SGE queues for Application SLEEP, version startdigit
Q: Submitting SLEEP.startdigit test-case 123Test to default SGE queue
S: SLEEP.startdigit test-case 123Test FAILED on abbeville : new results in errors,output
At 18:12 creating batch report for application SLEEP ...file written.
