TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.08Jun144355/QueueSystems/Limits/Master/KillTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version killing2
Submitting SLEEP test-suite TargetApp to LSF queues
  Submitting SLEEP test-case Basic to default LSF queue
Terminating testing due to external interruption
  Cancelling SLEEP test-case Basic in LSF (job 471297)
  SLEEP test-case Basic were terminated before completion (killed at 16:15) on forestville : differences in output
  View details(v), Save Version killing2(1), Save(s) or continue(any other key)?
