TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.13Jun125326/QueueSystems/Limits/Master/KillTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version killing2
Q: Submitting test Basic to default SGE queue
Terminating testing due to external interruption
T: Cancelling test Basic in SGE (job 13472)
S: Test Basic were terminated before completion (killed at 11:59) on placerville : differences in output
View details(v), Save Version killing2(1), Save(s) or continue(any other key)?
