TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/Limits/Master/KillTest based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version killing2
Q: Submitting SLEEP.killing2 test-case Basic to default SGE queue
Terminating testing due to external interruption
T: Cancelling SLEEP.killing2 test-case Basic in SGE (job 13472)
S: SLEEP.killing2 test-case Basic were terminated before completion (killed at 11:59) on placerville : differences in output
View details(v), Save Version killing2(1), Save(s) or continue(any other key)?
