TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/Limits/Master/KillTest based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/Limits/Master/KillTest/logging
Using LSF queues for Application SLEEP, version killing2
Q: Submitting SLEEP.killing2 test-case Basic to default LSF queue
Terminating testing due to external interruption
T: Cancelling SLEEP.killing2 test-case Basic in LSF (job 474624)
S: SLEEP.killing2 test-case Basic were terminated before completion (KILLED) on forestville : differences in output
View details(v), Save Version killing2(1), Save(s) or continue(any other key)?
