TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Slave/ReuseAddedApplication based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using Application HELLO, version 1, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Slave/ReuseAddedApplication/TargetApp/
Running HELLO.1 test-suite TargetApp
  Running HELLO.1 test-case Test
Comparing differences for HELLO.1 test-suite TargetApp
  Comparing differences for HELLO.1 test-case Test (on errors.hello,output.hello)
Using Application HELLO, version 2, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Slave/ReuseAddedApplication/TargetApp/
Running HELLO.2 test-suite TargetApp
  Running HELLO.2 test-suite Suite
    Running HELLO.2 test-case Test
Comparing differences for HELLO.2 test-suite TargetApp
  Comparing differences for HELLO.2 test-suite Suite
    Comparing differences for HELLO.2 test-case Test - SUCCESS! (on errors.hello,output.hello)
  Running HELLO.2 test-case Test
  Comparing differences for HELLO.2 test-case Test (on errors.hello,output.hello)
