TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct122319/texttest.sge/QueueSystems/SlaveReuse/Slave/ReuseAddedApplication based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using Application HELLO, version 1, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct122319/texttest.sge/QueueSystems/SlaveReuse/Slave/ReuseAddedApplication/TargetApp/
Running HELLO test-suite TargetApp
  Running HELLO test-case Test
Comparing differences for HELLO test-suite TargetApp
  Comparing differences for HELLO test-case Test (on errors.hello,output.hello)
Using Application HELLO, version 2, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct122319/texttest.sge/QueueSystems/SlaveReuse/Slave/ReuseAddedApplication/TargetApp/
Running HELLO test-suite TargetApp
  Running HELLO test-suite Suite
    Running HELLO test-case Test
Comparing differences for HELLO test-suite TargetApp
  Comparing differences for HELLO test-suite Suite
    Comparing differences for HELLO test-case Test - SUCCESS! (on errors.hello,output.hello)
  Running HELLO test-case Test
  Comparing differences for HELLO test-case Test (on errors.hello,output.hello)
