TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.13Jun125326/QueueSystems/NormalOperation/Console/TestNameWithDigit based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version startdigit
Q: Submitting test 123Test to default LSF queue
S: Test 123Test FAILED on forestville : new results in errors,output
View details(v), Save Version startdigit(1), Save(s) or continue(any other key)?
