TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.13Nov141742/texttest.sge/QueueSystems/NormalOperation/Console/TestNameWithDigit based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version startdigit
Q: Submitting SLEEP.startdigit test-case 123Test to default SGE queue
S: SLEEP.startdigit test-case 123Test succeeded on shelbyville
