TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.30Nov175319/QueueSystems/NormalOperation/Console/TestNameWithDigit based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version startdigit
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case 123Test to default SGE queue
  SLEEP test-case 123Test FAILED on granville : new results in errors,output
  View details(v), Save Version startdigit(1), Save(s) or continue(any other key)?
