TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.04Jul112329/QueueSystems/SlaveReuse/Master/ForceReuse/ClearEnvironment based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, version changeenv
Q: Submitting test Test under TargetApp to default SGE queue
S: Test Test under TargetApp FAILED on forestville : differences in output
View details(v), Save Version changeenv(1), Save(s) or continue(any other key)?
S: Test Test under Suite succeeded on forestville
