TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/ClearEnvironment based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, version changeenv, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/ClearEnvironment/TargetApp/
Q: Submitting HELLO.changeenv test-case Test to default SGE queue
S: HELLO.changeenv test-case Test FAILED on forestville : differences in output
View details(v), Save Version changeenv(1), Save(s) or continue(any other key)?
S: HELLO.changeenv test-case Test succeeded on forestville
