<-SRV:TextTest slave server started on 10.67.7.36:48343
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.kb -q non_existent -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/TargetApp -a sleep.kb -l -tp Basic -slave /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.27May152110.16447 -servaddr 127.0.0.1:34388 -b local""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.kb -q non_existent -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/TargetApp -a sleep.kb -l -tp Basic2 -slave /tmp/geoff/texttest.sge.27May152109.11165/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.27May152110.16447 -servaddr 127.0.0.1:34388 -b local""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
