<-SRV:TextTest slave server started on 10.67.7.148:35190
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.63157/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.20Dec105141.68282/slavelogs; qsub -N Test-Basic-SLEEP.kb -q non_existent -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.kb.log -e Test-Basic-SLEEP.kb.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.63157/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/TargetApp -a sleep.kb -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105139.63157/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.20Dec105141.68282 -servaddr 10.67.7.148:43588 -b local""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.63157/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.20Dec105141.68282/slavelogs; qsub -N Test-Basic2-SLEEP.kb -q non_existent -w e -notify -m n -cwd -b y -o Test-Basic2-SLEEP.kb.log -e Test-Basic2-SLEEP.kb.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.63157/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/TargetApp -a sleep.kb -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105139.63157/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.20Dec105141.68282 -servaddr 10.67.7.148:43588 -b local""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
