<-SRV:TextTest slave server started on 10.67.7.143:32987
<-CMD:cd /tmp/geoff/texttest.lsf.27May152122.26621/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/grid_core_files; bsub -J Test-Basic-SLEEP.kb -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152122.26621/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/TargetApp -a sleep.kb -l -tp Basic -slave /tmp/geoff/texttest.lsf.27May152122.26621/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.27May152124.29319 -servaddr 127.0.0.1:35585 -b local""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.lsf.27May152122.26621/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/grid_core_files; bsub -J Test-Basic2-SLEEP.kb -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152122.26621/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/TargetApp -a sleep.kb -l -tp Basic2 -slave /tmp/geoff/texttest.lsf.27May152122.26621/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/texttesttmp/local.kb.27May152124.29319 -servaddr 127.0.0.1:35585 -b local""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
