TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug based on file at /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/logging
Using LSF queues for Application SLEEP, version kb
Q: Submitting SLEEP.kb test-case Basic to LSF queue non_existent
S: SLEEP.kb test-case Basic not compared:  Test was trying to use a non-existent queue
Q: Submitting SLEEP.kb test-case Basic2 to LSF queue non_existent
S: SLEEP.kb test-case Basic2 not compared:  Test was trying to use a non-existent queue
At 15:20 creating batch report for application SLEEP ...
File written.
