TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug/logging
Using SGE queues for Application SLEEP, version kb
Q: Submitting SLEEP.kb test-case Basic to SGE queue non_existent
S: SLEEP.kb test-case Basic not compared:  Test was trying to use a non-existent queue
Q: Submitting SLEEP.kb test-case Basic2 to SGE queue non_existent
S: SLEEP.kb test-case Basic2 not compared:  Test was trying to use a non-existent queue
At 15:40 creating batch report for application SLEEP ...file written.
