TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueKnownBug based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version kb
Q: Submitting SLEEP.kb test-case Basic to SGE queue non_existent
S: SLEEP.kb test-case Basic not compared:  Test was trying to use a non-existent queue
Q: Submitting SLEEP.kb test-case Basic2 to SGE queue non_existent
S: SLEEP.kb test-case Basic2 not compared:  Test was trying to use a non-existent queue
At 17:34 creating batch report for application SLEEP ...file written.
