TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff22Sep151622/QueueSystems/ErrorHandling/Console/BadQueueKnownBug based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version kb
Submitting SLEEP test-suite TargetApp to LSF queues
  Submitting SLEEP test-case Basic  to LSF queue non_existent
  SLEEP test-case Basic  not compared:  Test was trying to use a non-existent queue
  Submitting SLEEP test-case Basic2 to LSF queue non_existent
  SLEEP test-case Basic2 not compared:  Test was trying to use a non-existent queue
At 15:16 creating batch report for application SLEEP ...file written
