TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff02Sep160045/QueueSystems/Console/ParallelNoPerfMatch based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version parallel.oneperf, checkout /users/geoff/texttesttmp/texttest.sgegeoff02Sep160045/QueueSystems/Console/ParallelNoPerfMatch/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Unexpected output from qsub : Called fake SGE with arguments -N geoff02Sep160103SLEEP.parallel.oneperfBasic -pe * 2 -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs
  Reading slave results for SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
