TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff11Feb16:40:23/QueueSystems/Console/ParallelNoPerfMatch based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version parallel.oneperf, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff11Feb16:40:23/QueueSystems/Console/ParallelNoPerfMatch/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Unexpected output from qsub : Called fake SGE with arguments -N geoff11Feb164034SLEEP.parallel.oneperfBasic -pe make 2 -w e -m n -b y -V -o /dev/null -e /dev/null
  Reading slave results for SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
