TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff14Jun093851/QueueSystems/Console/ExternalErrors/JobDisappearsAfterStart based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff14Jun093851/QueueSystems/Console/ExternalErrors/JobDisappearsAfterStart/TargetApp
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
  Cancelling SLEEP test-case Basic in SGE (job 4123581)
  SLEEP test-case Basic not compared:
no report, possibly killed with SIGKILL
Full accounting info from SGE follows:
Seriously nasty things happened while this test was running!

At 09:39 creating batch report for application SLEEP ...file written
