The following new files/directories were created:
<Test Directory>
----texttesttmp
--------console.absdata.queuesystem.06Mar152402.61663
------------slavelogs
----------------Test-Test2-TDAT.absdata.queuesystem.errors
----------------Test-Test2-TDAT.absdata.queuesystem.log
------------tdat.absdata.queuesystem
----------------Test2
--------------------errors.tdat
--------------------output.tdat
--------------------testdata.py
--------------------framework_tmp
------------------------catalogue.tdatorigcmp
------------------------errors.tdatcmp
------------------------errors.tdatorigcmp
------------------------output.tdatcmp
------------------------output.tdatorigcmp
