TextTest will write diagnostics in /nfs/vm/texttest-tmp/geoff/texttest.22Jan142908/texttest.sge/TestSelf/TestData/Console/AbsolutePathData based on file at /carm/proj/texttest-tmp/geoff/texttest.22Jan142908/texttest.sge/TestSelf/TestData/Console/AbsolutePathData/logging
Using Application TDAT, version absdata.queuesystem
Running TDAT.absdata.queuesystem test-suite TargetApp
  Running TDAT.absdata.queuesystem test-case Test2
Comparing differences for TDAT.absdata.queuesystem test-suite TargetApp
  Comparing differences for TDAT.absdata.queuesystem test-case Test2 (on errors.tdat,output.tdat,catalogue.tdat)
