#!/usr/bin/env python

import os, sys, string

cmdLine = string.join(sys.argv[1:])
if cmdLine.find("fake_machine1") != -1:
    print """job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------
1 0.50000 fake_job_n fakeuser1        r     06/15/2006 16:36:25 normal@fake_machine1.carmen.se              1        
       Full jobname:     fake_job_name_1
       Master queue:     normal@fake_machine1.carmen.se
       Hard Resources:   
       Soft Resources:   
2 0.50000 fake_job_n fakeuser2     r     06/29/2006 12:52:12 normal@fake_machine1.carmen.se              1        
       Full jobname:     fake_job_name_2
       Master queue:     normal@fake_machine1.carmen.se
       Hard Resources:   
       Soft Resources:
"""
else:
    print """job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------
3 0.50000 fake_job_n fakeuser2        r     06/15/2006 16:36:25 normal@fake_machine2.carmen.se              1        
       Full jobname:     fake_job_name_3
       Master queue:     normal@fake_machine2.carmen.se
       Hard Resources:   
       Soft Resources:   
4 0.50000 fake_job_n fakeuser4     r     06/29/2006 12:52:12 normal@fake_machine2.carmen.se              1        
       Full jobname:     fake_job_name_4
       Master queue:     normal@fake_machine2.carmen.se
       Hard Resources:   
       Soft Resources:
"""
