Using Application SLEEP
Reconnecting to test results in directory /carm/proj/texttest-tmp/geoff/texttest.sge.27Aug115825.19439/texttest.sge/QueueSystems/NormalOperation/Console/SlaveReconnectNoExtra/texttesttmp/batch_run.28Jan162616.20208/sleep
Reconnecting to SLEEP test-suite TargetApp
  Reconnecting to SLEEP test-case Basic2 (recomputing)
Comparing differences for SLEEP test-suite TargetApp
  Comparing differences for SLEEP test-case Basic2 - NONE!
