TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/NormalOperation/GUI/KillTests based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/NormalOperation/GUI/KillTests/logging
Using LSF queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default LSF queue
Q: Submitting SLEEP test-case Basic2 to default LSF queue
T: Cancelling SLEEP test-case Basic2 in LSF (job 7481)
T: Cancelling SLEEP test-case Basic in LSF (job 7480)
