TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/NormalOperation/GUI/KillTests based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/NormalOperation/GUI/KillTests/logging
Using SGE queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default SGE queue
Q: Submitting SLEEP test-case Basic2 to default SGE queue
T: Cancelling SLEEP test-case Basic2 in SGE (job 28862)
T: Cancelling SLEEP test-case Basic in SGE (job 28859)
