TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.13Jun115925/QueueSystems/NormalOperation/GUI/KillTests based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP
Q: Submitting test Basic to default SGE queue
Q: Submitting test Basic2 to default SGE queue
T: Cancelling test Basic2 in SGE (job 7481)
T: Cancelling test Basic in SGE (job 7480)
