TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/NormalOperation/GUI/KillTests based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default SGE queue
Q: Submitting SLEEP test-case Basic2 to default SGE queue
T: Cancelling SLEEP test-case Basic2 in SGE (job 7481)
T: Cancelling SLEEP test-case Basic in SGE (job 7480)
