TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff23Feb170853/TestSelf/MemoryTests/Console/ExtractStandardPerformance based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application MEM, version nomemfile.lsf, checkout /users/geoff/texttesttmp/texttest.lsfgeoff23Feb170853/TestSelf/MemoryTests/Console/ExtractStandardPerformance/TargetApp/
Extracting standard performance for MEM test-suite TargetApp
  Extracting standard performance for MEM test-case NoMemFile
