TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff03Mar165812/TestSelf/MemoryTests/Console/ExtractStandardPerformance based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application MEM, version nomemfile.lsf, checkout /nfs/vm/texttest/central_texttesttmp/texttest.lsfgeoff03Mar165812/TestSelf/MemoryTests/Console/ExtractStandardPerformance/TargetApp/./
Extracting standard performance for MEM test-suite TargetApp
  Extracting standard performance for MEM test-case NoMemFile
