<-SRV:TextTest slave server started on 10.67.7.36:39162
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.20874/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/texttesttmp/dynamic_gui.20Dec105130.26049/slavelogs; qsub -N Test-Test-HELLO -w e -notify -m n -cwd -b y -v DISPLAY -o Test-Test-HELLO.log -e Test-Test-HELLO.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.20874/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/TargetApp -a hello -l -tp Test -slave /tmp/geoff/texttest.sge.20Dec105121.20874/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/texttesttmp/dynamic_gui.20Dec105130.26049 -servaddr 10.67.7.36:48555""
->OUT:Your job 9019 ("Test-Test-HELLO") has been submitted
<-SRV:Completed submission of tests up to capacity
<-CMD:qdel 9019
->OUT:somebody has deleted job 9019
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.20874/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/texttesttmp/dynamic_gui.20Dec105130.26049/slavelogs; qsub -N Test-Test.Suite-HELLO -w e -notify -m n -cwd -b y -v DISPLAY -o Test-Test.Suite-HELLO.log -e Test-Test.Suite-HELLO.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.20874/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/TargetApp -a hello -l -tp Suite/Test -slave /tmp/geoff/texttest.sge.20Dec105121.20874/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/texttesttmp/dynamic_gui.20Dec105130.26049 -servaddr 10.67.7.36:48555""
->OUT:Your job 9019 ("Test-Test-HELLO") has been submitted
<-SRV:Completed submission of tests up to capacity
<-SRV:Completed submission of all tests
