TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct105542/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct105542/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
T: Cancelling HELLO test-case Test in SGE (job 9019)
Q: Submitting HELLO test-case Test to default SGE queue
