TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff06Oct122521/QueueSystems/Console/ExternalErrors/JobSubmissionFails based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff06Oct122521/QueueSystems/Console/ExternalErrors/JobSubmissionFails/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Received signal for termination, killing all remaining tests...
  Cancelling SLEEP test-case Basic in SGE (Emergency finish of job 1)
  SLEEP test-case Basic not compared:  SGE/system error
Full accounting info from SGE follows:
Your job was sent into a large mysterious void. Bad luck.

At 12:25 creating batch report for application SLEEP ...file written
