TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/ExternalErrors/JobSubmissionFails based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/ExternalErrors/JobSubmissionFails/TargetApp/
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
  Cancelling SLEEP test-case Basic in SGE (job 1)
  SLEEP test-case Basic not compared:  SGE/system error
Full accounting info from SGE follows:
Your job was sent into a large mysterious void. Bad luck.

At 17:35 creating batch report for application SLEEP ...file written
