TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff10Jul105727/QueueSystems/Console/TestNameWithDigit based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version startdigit
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case 123Test to default SGE queue
  Evaluating SLEEP test-case 123Test (on errors.sleep,output.sleep)
  SLEEP test-case 123Test FAILED on knoxville : new results in errors,output
  View details(v), Save Version startdigit(1), Save(s) or continue(any other key)?
