TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff10Jul105727/QueueSystems/Console/BadPerformanceModel based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badperfarch
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  SLEEP test-case Basic  not compared:  Failed to submit to SGE (Unable to run job: error: no suitable queues.)
  Submitting SLEEP test-case Basic2 to default SGE queue
  SLEEP test-case Basic2 not compared:  Failed to submit to SGE (Unable to run job: error: no suitable queues.)
