TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff27Jan11:47:05/lsf/BadPerformanceModel based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badperfmodel, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff27Jan11:47:05/lsf/BadPerformanceModel/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  Submitting SLEEP test-case Basic2 to default SGE queue
  SLEEP test-case Basic  not compared:  Failed to submit to SGE (Unable to run job: error: no suitable queues.)
  SLEEP test-case Basic2 not compared:  Failed to submit to SGE (Unable to run job: error: no suitable queues.)
