#!/usr/bin/env python

import sys
print "Fake gcc failed to build! Printing lots of crap..."
# Make the error message disappear...
for i in range(50):
    print "Crap", i
print "Here is the real error message"
sys.exit(1)
