TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.04Jul143732/QueueSystems/SlaveReuse/Master/ForceReuse/KillReusedTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /users/geoff/texttesttmp/texttest.sge.04Jul143732/QueueSystems/SlaveReuse/Master/ForceReuse/KillReusedTest/TargetApp/
Q: Submitting test Test under TargetApp to default SGE queue
T: Cancelling test Test under Suite in SGE (job 25617)
