TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/KillReusedTest based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/KillReusedTest/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
T: Cancelling HELLO test-case Test in SGE (job 25617)
