Using SGE queues for Application SLEEP, version killing3
Q: Submitting SLEEP.killing3 test-case Basic to default SGE queue
S: SLEEP.killing3 test-case Basic were terminated before completion (RUNLIMIT) on dolgeville : differences in output
Results:

Tests that did not succeed:
  SLEEP.killing3 test-case Basic were terminated before completion (RUNLIMIT) on dolgeville : differences in output

Tests Run: 1, Incomplete: 1
Creating batch report for application SLEEP ...
File written.
