TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/NormalOperation/Console/SlaveTransferFlags based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/NormalOperation/Console/SlaveTransferFlags/logging
Using SGE queues for Application SLEEP, version startdigit
Q: Submitting SLEEP.startdigit test-case 123Test to default SGE queue
S: SLEEP.startdigit test-case 123Test succeeded on forestville
