TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff19Jan17:39:06/TestSelf/EnvironmentFile/RemoveSuiteVars based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application Env Variables, version lsf, checkout /nfs/vm/texttest/central_texttesttmp/texttest.lsfgeoff19Jan17:39:06/TestSelf/EnvironmentFile/RemoveSuiteVars/TargetApp/./
Submitting Env Variables test-suite TargetApp to LSF queues
  Submitting Env Variables test-suite Suite1 to LSF queues
    Submitting Env Variables test-case Test1 to LSF queue normal
  Submitting Env Variables test-case Test2  to LSF queue normal
  Reading slave results for Env Variables test-case Test2  - SUCCESS! (on errors.env.lsf,output.env)
    Reading slave results for Env Variables test-case Test1 - SUCCESS! (on errors.env.lsf,output.env)
