TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/BatchTestNotInParent based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/BatchTestNotInParent/TargetApp
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic3 to default SGE queue
  Evaluating SLEEP test-case Basic3 (on errors.sleep,output.sleep)
  SLEEP test-case Basic3 FAILED on statesville : new results in errors,output
At 17:35 creating batch report for application SLEEP ...file written
