TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff11Apr171107/QueueSystems/Console/BatchTestNotInParent based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff11Apr171107/QueueSystems/Console/BatchTestNotInParent/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic3 to default SGE queue
  Reading slave results for SLEEP test-case Basic3 (on errors.sleep,output.sleep)
  SLEEP test-case Basic3 FAILED on pennsville : new results in errors,output
At 17:14 creating batch report for application SLEEP ...file written
