TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff10Jul105727/QueueSystems/Console/BatchTestNotInParent based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic3 to default SGE queue
  Evaluating SLEEP test-case Basic3 (on errors.sleep,output.sleep)
  SLEEP test-case Basic3 FAILED on brockville : new results in errors,output
At 10:59 creating batch report for application SLEEP ...file written
