#!/bin/sh
echo "A weird and unexpected error message" 1>&2
echo "JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME"
echo "1  $USER   EXIT  bad_machine_queue     bad_machine bad_machine fake_name       Sep  7 15:37"
