<-SRV:TextTest slave server started on 10.80.19.195:57827
<-CMD:cd /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/texttesttmp/grid_core_files; qsub -N Test-Test-HELLO -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/TargetApp -a hello -l -tp Test -slave /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/texttesttmp/self_test.22Jan110452.2545 -servaddr 127.0.0.1:59284 -b self_test""
->OUT:Your job 28856 ("Test-Test-HELLO") has been submitted
<-SRV:Completed submission of tests up to capacity
<-SRV:Completed submission of all tests
<-CMD:qstat
<-CMD:qacct -j 28856
->OUT:Some account info
<-CMD:cd /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/texttesttmp/grid_core_files; qsub -N Test-Test.Suite-HELLO -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/TargetApp -a hello -l -tp Suite/Test -slave /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/BatchAvoidDeadlock/texttesttmp/self_test.22Jan110452.2545 -servaddr 127.0.0.1:59284 -b self_test""
->OUT:Your job 28857 ("Test-Test-HELLO") has been submitted
<-SRV:Completed submission of tests up to capacity
<-CMD:qstat
<-CMD:qacct -j 28857
->OUT:Other account info
