TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff13Oct160503/QueueSystems/Console/Parallel/NoPerfMatch based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version parallel.oneperf, checkout /users/geoff/texttesttmp/texttest.sgegeoff13Oct160503/QueueSystems/Console/Parallel/NoPerfMatch/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Evaluating SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
