TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff05Oct120258/QueueSystems/Console/Parallel/NoPerfMatch based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version parallel.oneperf, checkout /users/geoff/texttesttmp/texttest.sgegeoff05Oct120258/QueueSystems/Console/Parallel/NoPerfMatch/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Unexpected output from qsub : Called fake SGE with arguments -N geoff05Oct120724SLEEP.parallel.oneperfBasic -pe * 2 -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs
  Evaluating SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
