<-SRV:TextTest slave server started on 10.67.7.142:37596
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobDisappears/texttesttmp/sleep.killing.20Dec105138.18252/slavelogs; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT bsub -J Test-Basic-SLEEP.killing -u nobody -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobDisappears/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobDisappears/texttesttmp/sleep.killing.20Dec105138.18252 -servaddr 10.67.7.142:33618 -b short_local""
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:bjobs -a -l 1
->ERR:Job <1> is not found
