TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff04Feb14:49:57/QueueSystems/Console/ResourceUsageRequest based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff04Feb14:49:57/QueueSystems/Console/ResourceUsageRequest/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Reading slave results for SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
