TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.19Oct154401/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/MasterResetsConnection based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version startdigit
Running SLEEP.startdigit test-suite TargetApp
  Running SLEEP.startdigit test-case 123Test
Comparing differences for SLEEP.startdigit test-suite TargetApp
  Comparing differences for SLEEP.startdigit test-case 123Test - SUCCESS! (on errors.sleep,output.sleep)
Terminating as failed to read response from master process, got error :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/queuesystem.py", line 70, in notifyLifecycleChange
    response = sendSocket.makefile().read()
  File "/carm/proj/texttest/geoff/texttesttmp/texttest.19Oct154401/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/MasterResetsConnection/interceptor.py", line 11, in makefile
    raise socket.error, "Connection reset by peer"
error: Connection reset by peer

