TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff27Jan10:31:49/lsf/NumericResourceRequest based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff27Jan10:31:49/lsf/NumericResourceRequest/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Reading slave results for SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
