TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff23May120616/QueueSystems/Console/ExternalErrors/JobDisappears based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff23May120616/QueueSystems/Console/ExternalErrors/JobDisappears/TargetApp/
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
  Cancelling SLEEP test-case Basic in SGE (job 1)
  SLEEP test-case Basic not compared:
SGE/system error
Full accounting info from SGE follows:
SGE lost job:1
 qdel output was as follows:
denied: job 1 does not exist

At 12:09 creating batch report for application SLEEP ...file written
