TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.11Oct180920/QueueSystems/Limits/Master/NightjobTerminate based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
  Cancelling SLEEP test-case Basic in SGE (job 4916817)
  SLEEP test-case Basic were terminated before completion (killed at 15:03) on townsville : differences in output
At 18:11 creating batch report for application SLEEP ...file written.
