TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/Limits/Master/NightjobTerminate based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/Limits/Master/NightjobTerminate/logging
Using LSF queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default LSF queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling SLEEP.killing test-case Basic in LSF (job 471285)
S: SLEEP.killing test-case Basic were terminated before completion (killed at 15:27) on forestville : differences in output
At 15:40 creating batch report for application SLEEP ...file written.
