TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.13Jun123443/QueueSystems/Limits/Master/NightjobTerminate based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version killing
Q: Submitting test Basic to default LSF queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling test Basic in LSF (job 471285)
S: Test Basic were terminated before completion (killed at 15:27) on forestville : differences in output
At 12:35 creating batch report for application SLEEP ...file written.
