Using SGE queues for Application HELLO, version resource, checkout /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ResourcesOverReuse/TargetApp/
Q: Submitting HELLO.resource test-case Test to default SGE queue
S: HELLO.resource test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Approve Version resource(1), Approve(a) or continue(any other key)?
Q: Submitting HELLO.resource test-case Test to default SGE queue
S: HELLO.resource test-case Suite/Test not compared:
Failed to submit to SGE (Unable to run job: unknown resource "no_such_resource".)
Submission command was 'qsub -N Test-Test.Suite-HELLO.resource -l no_such_resource -w e -notify -m n -cwd -b y -v STANDARD,DISPLAY -o /dev/null -e /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ResourcesOverReuse/texttesttmp/grid_core_files/slave_start_errors.matlar exec $SHELL ... '

