<-SRV:TextTest slave server started on 10.67.6.208:56840
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.19002/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachine/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP -l hostname=no_such_machine -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.19002/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachine/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105139.19002/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachine/texttesttmp/console.20Dec105142.19676 -servaddr 10.67.6.208:59394""
->ERR:Unable to run job: can't resolve hostname "no_such_machine".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.19002/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachine/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP -l hostname=no_such_machine -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.19002/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachine/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105139.19002/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachine/texttesttmp/console.20Dec105142.19676 -servaddr 10.67.6.208:59394""
->ERR:Unable to run job: can't resolve hostname "no_such_machine".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
