TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.04Jun112711/QueueSystems/Limits/Slave/RunLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version killing
Running SLEEP test-suite TargetApp
  Running SLEEP test-case Basic
Terminating testing due to external interruption (RUNLIMIT1)
Killing running test (process id 6015)
Comparing differences for SLEEP test-suite TargetApp
  Comparing differences for SLEEP test-case Basic (on errors.sleep,output.sleep)
  SLEEP test-case Basic were terminated before completion (RUNLIMIT) on connellsville : differences in output
