TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.lsf/QueueSystems/Limits/Slave/RunLimit based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version killing
Running SLEEP.killing test-suite TargetApp
  Running SLEEP.killing test-case Basic
Terminating testing due to external interruption (RUNLIMIT2)
Killing running test (process id 19856)
Comparing differences for SLEEP.killing test-suite TargetApp
  Comparing differences for SLEEP.killing test-case Basic (on errors.sleep,output.sleep)
