TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.27Jun174608/QueueSystems/Limits/Slave/RunLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version killing
Running SLEEP test-suite TargetApp
  Running SLEEP test-case Basic
Terminating testing due to external interruption (RUNLIMIT1)
Killing running test (process id 12552)
Comparing differences for SLEEP test-suite TargetApp
  Comparing differences for SLEEP test-case Basic (on errors.sleep,output.sleep)
