TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.02Oct160717/texttest.sge/QueueSystems/Limits/Slave/RunLimit based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version killing
Running SLEEP.killing test-suite TargetApp
  Running SLEEP.killing test-case Basic
Terminating testing due to external interruption (RUNLIMIT1)
Killing running test (process id 6719)
Comparing differences for SLEEP.killing test-suite TargetApp
  Comparing differences for SLEEP.killing test-case Basic (on errors.sleep,output.sleep)
