<-SRV:TextTest slave server started on 10.67.6.149:44083
<-CMD:cd /tmp/geoff/texttest.sge.signals.27May152111.118686/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.signals.27May152111.118686/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.signals.27May152111.118686/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.signals.27May152111.118686/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/sleep.killing.27May152113.1494 -servaddr 127.0.0.1:54732 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job "1" does not exist
<-CMD:qacct -j 1
->OUT:Your job was sent into a large mysterious void. Bad luck.
