<-SRV:TextTest slave server started on 10.67.7.144:42245
<-CMD:cd /tmp/geoff/texttest.lsf.signals.27May152123.17973/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/grid_core_files; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT bsub -J Test-Basic-SLEEP.killing -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.signals.27May152123.17973/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.lsf.signals.27May152123.17973/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/sleep.killing.27May152125.20562 -servaddr 127.0.0.1:55337 -b short_local""
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:bjobs -a -l 1
->OUT:Your job was sent into a large mysterious void. Bad luck.
