<-SRV:TextTest slave server started on 10.67.7.142:57935
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15168/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/sleep.killing.20Dec105138.18248/slavelogs; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT bsub -J Test-Basic-SLEEP.killing -u nobody -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15168/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.15168/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/sleep.killing.20Dec105138.18248 -servaddr 10.67.7.142:48329 -b short_local""
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:bjobs -a -l 1
->OUT:Your job was sent into a large mysterious void. Bad luck.
