<-SRV:TextTest slave server started on 10.67.7.142:49278
<-CMD:cd /tmp/geoff/texttest.sge.signals.20Dec105156.18983/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/sleep.killing.20Dec105157.20932/slavelogs; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.signals.20Dec105156.18983/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.signals.20Dec105156.18983/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobSubmissionFails/texttesttmp/sleep.killing.20Dec105157.20932 -servaddr 10.67.7.142:53748 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job "1" does not exist
<-CMD:qacct -j 1
->OUT:Your job was sent into a large mysterious void. Bad luck.
