TextTest will write diagnostics in /nfs/vm/texttest-tmp/geoff/texttest.sge.sge.12May163211.22650/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillBeforeReuse based on file at /carm/proj/texttest-tmp/geoff/texttest.sge.sge.12May163211.22650/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillBeforeReuse/logging
Using SGE queues for Application HELLO, checkout /carm/proj/texttest-tmp/geoff/texttest.sge.sge.12May163211.22650/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillBeforeReuse/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
T: Cancelling HELLO test-case Test in SGE (job 2311975)
