<-SRV:TextTest slave server started on 192.168.99.53:47639
<-CMD:cd /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappearsAfterStart/texttesttmp/sleep.killing.11Sep114049/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' bsub -J Test-Basic-SLEEP.killing -u nobody -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappearsAfterStart/TargetApp -a sleep -v killing -l -tp Basic -slave /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappearsAfterStart/texttesttmp/sleep.killing.11Sep114049 -servaddr 192.168.99.53:47636 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobDisappearsAfterStart/slave"'
->OUT:Job <1> is submitted to queue <fake_machine_queue>.
<-SRV:Completed submission of all tests
->CLI:25852
sleep.killing:Basic
(idefault
Running
p1
(dp2
S'category'
p3
S'running'
p4
sS'bkgProcess'
p5
NsS'freeText'
p6
S'Running on fake_machine1'
p7
sS'started'
p8
I1
sS'completed'
p9
I0
sS'briefText'
p10
S'RUN (fake_machine1)'
p11
sS'executionHosts'
p12
(lp13
S'fake_machine1'
p14
asS'lifecycleChange'
p15
S'start'
p16
sb.
<-CMD:bkill -s USR1 1
->ERR:No jobs can be deleted today!
<-CMD:bjobs -a -l 1
->OUT:Seriously nasty things happened while this test was running!
