TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff02Mar114746/QueueSystems/Console/ExternalErrors/JobStaysPending based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing, checkout /users/geoff/texttesttmp/texttest.sgegeoff02Mar114746/QueueSystems/Console/ExternalErrors/JobStaysPending/TargetApp/
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
  Cancelling SLEEP test-case Basic in SGE (job 1)
  SLEEP test-case Basic not compared:  Test job was killed (while still pending in SGE) at 11:47
At 11:47 creating batch report for application SLEEP ...file written
