TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.lsf/QueueSystems/ErrorHandling/Console/JobStaysPending based on file at /carm/proj/texttest-tmp/geoff/texttest.26May151930.24974/texttest.lsf/QueueSystems/ErrorHandling/Console/JobStaysPending/logging
Using LSF queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default LSF queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling SLEEP.killing test-case Basic in LSF (job 1)
S: SLEEP.killing test-case Basic not compared:  Test job was cancelled (while still pending in LSF) at 15:20
At 15:20 creating batch report for application SLEEP ...
File written.
