TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/Console/JobStaysPending based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/Console/JobStaysPending/logging
Using SGE queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling SLEEP.killing test-case Basic in SGE (job 1)
S: SLEEP.killing test-case Basic not compared:  Test job was cancelled (while still pending in SGE) at 15:40
At 15:40 creating batch report for application SLEEP ...file written.
