TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.13Jun123443/QueueSystems/ErrorHandling/Console/JobStaysPending based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version killing
Q: Submitting test Basic to default LSF queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling test Basic in LSF (job 1)
S: Test Basic not compared:  Test job was cancelled (while still pending in LSF) at 12:35
At 12:35 creating batch report for application SLEEP ...file written.
