<-SRV:TextTest slave server started on 192.168.99.65:51133
<-CMD:cd /users/geoff/texttesttmp/texttest.sge.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/texttesttmp/sleep.killing.10Sep163646/sleep.killing/Basic; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic-SLEEP.killing -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.sge.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/TargetApp -a sleep -v killing -l -tp Basic -slave /users/geoff/texttesttmp/texttest.sge.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/texttesttmp/sleep.killing.10Sep163646 -servaddr 192.168.99.65:51131 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/slave"'
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:somebody has deleted job 1
