<-SRV:TextTest slave server started on 192.168.99.73:57069
<-CMD:cd /users/geoff/texttesttmp/texttest.lsf.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/texttesttmp/sleep.killing.10Sep163655/sleep.killing/Basic; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' bsub -J Test-Basic-SLEEP.killing -u nobody -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.lsf.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/TargetApp -a sleep -v killing -l -tp Basic -slave /users/geoff/texttesttmp/texttest.lsf.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/texttesttmp/sleep.killing.10Sep163655 -servaddr 192.168.99.73:57062 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.lsf.10Sep163632/QueueSystems/ErrorHandling/Console/JobStaysPending/slave"'
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->OUT:Job <1> is being terminated
