<-SRV:TextTest slave server started on 192.168.99.34:42118
<-CMD:cd /nfs/vm/texttest-tmp/geoff/dynamic_gui.03Jun141458.5821/texttest.lsf/QueueSystems/ErrorHandling/Console/JobStaysPending/texttesttmp/sleep.killing.03Jun141516.23632/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' bsub -J Test-Basic-SLEEP.killing -u nobody -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors 'exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.03Jun141458.5821/texttest.lsf/QueueSystems/ErrorHandling/Console/JobStaysPending/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.03Jun141458.5821/texttest.lsf/QueueSystems/ErrorHandling/Console/JobStaysPending/texttesttmp/sleep.killing.03Jun141516.23632 -servaddr 192.168.99.34:42044 -b short_local"'
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->OUT:Job <1> is being terminated
