#!/usr/bin/env python

import os, sys, string, time

def getBsubs():
    bsubs = []
    for dir in os.environ["PATH"].split(os.pathsep):
        fullPath = os.path.join(dir, "bsub")
        if os.path.isfile(fullPath) and not fullPath in bsubs:
            bsubs.append(fullPath)
    return bsubs

def getRealBsub():
    bsubs = getBsubs()
    if len(bsubs) > 1:
        return bsubs[1]
    else:
        return bsubs[0]

print "Calling LSF with synchronise mode on..."
# Run the slave locally, to avoid delays
os.system(getRealBsub() + " -K " + string.join(sys.argv[1:-1]) + " '" + sys.argv[-1] + "' > /dev/null 2>&1")
# Wait for files to propagate in NFS...
time.sleep(1)
