#!/usr/bin/env python

import os, sys, string, time

def getQsubs():
    qsubs = []
    for dir in os.environ["PATH"].split(os.pathsep):
        fullPath = os.path.join(dir, "qsub")
        if os.path.isfile(fullPath) and not fullPath in qsubs:
            qsubs.append(fullPath)
    return qsubs

def getRealQsub():
    qsubs = getQsubs()
    if len(qsubs) > 1:
        return qsubs[1]
    else:
        return qsubs[0]

print "Calling SGE with synchronise mode on..."
# Run the slave locally, to avoid delays
os.system(getRealQsub() + " -sync y " + string.join(sys.argv[1:-1]) + " '" + sys.argv[-1] + "'")
# Wait for files to propagate in NFS...
time.sleep(1)
