TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.29Aug103708/QueueSystems/SlaveReuse/Slave/VirtualDisplay/AddApplication based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application HELLO, version gui.1, checkout /users/geoff/texttesttmp/texttest.sge.29Aug103708/QueueSystems/SlaveReuse/Slave/VirtualDisplay/AddApplication/TargetApp/
Tests will run with DISPLAY variable set to localhost:3979.0
Running HELLO test-suite TargetApp
  Running HELLO test-case Test
Comparing differences for HELLO test-suite TargetApp
  Comparing differences for HELLO test-case Test (on errors.hello,output.hello)
Using Application HELLO, version gui.2, checkout /users/geoff/texttesttmp/texttest.sge.29Aug103708/QueueSystems/SlaveReuse/Slave/VirtualDisplay/AddApplication/TargetApp/
Running HELLO test-suite TargetApp
  Running HELLO test-suite Suite
    Running HELLO test-case Test
Comparing differences for HELLO test-suite TargetApp
  Comparing differences for HELLO test-suite Suite
    Comparing differences for HELLO test-case Test - SUCCESS! (on errors.hello,output.hello.gui)
Killing Xvfb process 7699
