TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Slave/VirtualDisplay/AddApplication based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using Application HELLO, version gui.1, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Slave/VirtualDisplay/AddApplication/TargetApp/
Tests will run with DISPLAY variable set to localhost:3979.0
Running HELLO.gui.1 test-suite TargetApp
  Running HELLO.gui.1 test-case Test
Comparing differences for HELLO.gui.1 test-suite TargetApp
  Comparing differences for HELLO.gui.1 test-case Test (on errors.hello,output.hello)
Using Application HELLO, version gui.2, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Slave/VirtualDisplay/AddApplication/TargetApp/
Running HELLO.gui.2 test-suite TargetApp
  Running HELLO.gui.2 test-suite Suite
    Running HELLO.gui.2 test-case Test
Comparing differences for HELLO.gui.2 test-suite TargetApp
  Comparing differences for HELLO.gui.2 test-suite Suite
    Comparing differences for HELLO.gui.2 test-case Test - SUCCESS! (on errors.hello,output.hello.gui)
Killing Xvfb process 30113
Process had already terminated
