#!/usr/bin/env python

print """
SECTION apc_status input
 TOTAL cost....................................:        22
Time:  0 s real  50 ms cpu  0 ms cpu_child  memory:  24.8 Mb

SECTION apc_status Solution_1
Total time:  0:00:00   cpu time:  0:01:00
 TOTAL cost....................................:        8
Time:  0 s real  100 ms cpu  0 ms cpu_child  memory:  38.5 Mb

SECTION apc_status Solution_2
Total time:  0:00:00   cpu time:  0:02:00
 TOTAL cost....................................:        7
Time:  0 s real  130 ms cpu  0 ms cpu_child  memory:  38.5 Mb

SECTION apc_status Solution_3
Total time:  0:00:00   cpu time:  0:03:00
 TOTAL cost....................................:        6
Time:  0 s real  180 ms cpu  0 ms cpu_child  memory:  38.6 Mb

SECTION apc_status Solution_4
Total time:  0:00:01   cpu time:  0:04:00
 TOTAL cost....................................:        12
Time:  1 s real  960 ms cpu  0 ms cpu_child  memory:  39.3 Mb

SECTION apc_status Solution_5
Total time:  0:00:01   cpu time:  0:05:00
 TOTAL cost....................................:        6
Time:  1 s real  970 ms cpu  10 ms cpu_child  memory:  32.4 Mb"""
