TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff21Aug122338/QueueSystems/ErrorHandling/GUI/SlaveCrash based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badslave
WARNING : caught exception while running SLEEP test-case Basic changing state to UNRUNNABLE :
  SLEEP test-case Basic not compared:
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/engine.py", line 33, in handleExceptions
    return method(*args)
  File "/users/geoff/work/master/Testing/TextTest/testmodel.py", line 392, in callAction
    return action(self)
  File "/users/geoff/work/master/Testing/Automatic/texttest/error_config_modules/slaveerr.py", line 18, in __call__
    wibble
NameError: global name 'wibble' is not defined

