<-SRV:TextTest slave server started on 10.67.7.142:41131
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15168/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/self_test.20Dec105127.17852/slavelogs; qsub -N Test-Test-HELLO -w e -notify -m n -cwd -b y -o Test-Test-HELLO.log -e Test-Test-HELLO.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15168/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/TargetApp -a hello -l -tp Test -slave /tmp/geoff/texttest.sge.20Dec105121.15168/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/self_test.20Dec105127.17852 -servaddr 10.67.7.142:52204 -b self_test""
->OUT:Your job 121427 ("Test-Test-HELLO") has been submitted
<-SRV:Completed submission of tests up to capacity
<-CMD:qdel 121427
->OUT:geoff has deleted job 121427
<-SRV:Completed submission of all tests
