<-SRV:TextTest slave server started on 10.80.19.154:39953
<-CMD:cd /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/grid_core_files; qsub -N Test-Test-HELLO -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/TargetApp -a hello -l -tp Test -slave /carm/proj/texttest-tmp-mc/geoff/dynamic_gui.22Jan170325.7230/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/self_test.22Jan110454.5756 -servaddr 127.0.0.1:53764 -b self_test""
->OUT:Your job 121427 ("Test-Test-HELLO") has been submitted
<-SRV:Completed submission of tests up to capacity
<-SRV:Completed submission of all tests
<-CMD:qdel 121427
->OUT:geoff has deleted job 121427
