<-SRV:TextTest slave server started on 10.67.6.149:59486
<-CMD:cd /tmp/geoff/texttest.sge.signals.27May152111.118672/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/grid_core_files; qsub -N Test-Test-HELLO -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.signals.27May152111.118672/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.signals.27May152111.118672/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/TargetApp -a hello -l -tp Test -slave /tmp/geoff/texttest.sge.signals.27May152111.118672/texttest.sge.signals/QueueSystems/SlaveReuse/Master/ForceReuse/Signals/CancelBeyondCapacity/texttesttmp/self_test.27May152113.1483 -servaddr 127.0.0.1:43862 -b self_test""
->OUT:Your job 121427 ("Test-Test-HELLO") has been submitted
<-SRV:Completed submission of tests up to capacity
<-CMD:qdel 121427
->OUT:geoff has deleted job 121427
<-SRV:Completed submission of all tests
