#!/usr/bin/env python

import sys, os
from getopt import getopt

output = """real 7.02
user 3.5
sys 1.5
"""

options, args = getopt(sys.argv[1:], "po:")
os.spawnvp(os.P_WAIT, args[0], args)

perfFile = dict(options).get("-o")
targetFile = open(perfFile, "w")
targetFile.write(output)
targetFile.close()
