TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff22Sep145739/QueueSystems/Console/KillTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing2, checkout /users/geoff/texttesttmp/texttest.sgegeoff22Sep145739/QueueSystems/Console/KillTest/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Cancelling SLEEP test-case Basic in SGE (job 1217179)
Terminated due to interruption
