TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff01Nov195954/QueueSystems/Console/KillTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing2, checkout /users/geoff/texttesttmp/texttest.sgegeoff01Nov195954/QueueSystems/Console/KillTest/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption
  Cancelling SLEEP test-case Basic in SGE (job 1591396)
  SLEEP test-case Basic were terminated before completion (killed at 20:00) on woodville : differences in output
  View details(v), Save Version killing2(1), Save(s) or continue(any other key)?
