TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff12Apr161229/QueueSystems/Console/KillTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing2, checkout /users/geoff/texttesttmp/texttest.sgegeoff12Apr161229/QueueSystems/Console/KillTest/TargetApp
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption
  Cancelling SLEEP test-case Basic in SGE (job 3363099)
