Using SGE queues for Application HELLO, checkout /tmp/geoff/texttest.sge.27May152108.4447/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/NoReuseWithProxy/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Approve(a) or continue(any other key)?
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test not compared:
Failed to submit to SGE (Unable to run job: unknown resource "no_such_resource".)
Submission command was 'qsub -N Test-Test.Suite-HELLO -w e -notify -m n -cwd -b y -v TEXTTEST_SUBMIT_COMMAND_ARGS -o /dev/null -e /tmp/geoff/texttest.sge.27May152108.4447/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/NoReuseWithProxy/texttesttmp/grid_core_files/slave_start_errors.geoff ... '

