Using SGE queues for Application HELLO, version parallel, checkout /tmp/geoff/texttest.25May172628.533/texttest.sge/QueueSystems/SlaveReuse/Master/AllowRacing/RespectParallel/TargetApp/
Q: Submitting HELLO.parallel test-case Test to default SGE queue
Waiting Q thread for 5 seconds
Q: Submitting HELLO.parallel test-case Test to default SGE queue
S: HELLO.parallel test-case Test FAILED on titusville : differences in output
View details(v), Approve Version parallel(1), Approve(a) or continue(any other key)?
S: HELLO.parallel test-case Test succeeded on graceville, schefferville
