TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.05Jul143738/QueueSystems/SlaveReuse/Master/AllowRacing/RespectParallel based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, version parallel, checkout /users/geoff/texttesttmp/texttest.sge.05Jul143738/QueueSystems/SlaveReuse/Master/AllowRacing/RespectParallel/TargetApp/
Q: Submitting test Test under TargetApp to default SGE queue
Waiting Q thread for 5 seconds
Q: Submitting test Test under Suite to default SGE queue
S: Test Test under TargetApp FAILED on titusville : differences in output
View details(v), Save Version parallel(1), Save(s) or continue(any other key)?
S: Test Test under Suite succeeded on graceville,schefferville
