#!/usr/bin/env python
import sys, string, os
if string.join(sys.argv).find("-s z") != -1:
    print "job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID "
    print "-----------------------------------------------------------------------------------------------------------------"
    print "1   0.00000 stupid       $USER        Eqw    02/02/2005 17:27:22   bad_queue@bad_machine.carmen.se       1        "
