<-SRV:TextTest slave server started on 10.67.7.36:34068
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105122.20896/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.20Dec105131.26084/slavelogs; qsub -N Test-Test1.Suite1-HELLO -w e -notify -m n -cwd -b y -v DISPLAY -o Test-Test1.Suite1-HELLO.log -e Test-Test1.Suite1-HELLO.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105122.20896/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/TargetApp -a hello -l -tp Suite1/Test1 -slave /tmp/geoff/texttest.sge.20Dec105122.20896/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.20Dec105131.26084 -servaddr 10.67.7.36:37573""
->OUT:Your job 8512 ("Test-Test1.Suite1-HELLO") has been submitted
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105122.20896/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.20Dec105131.26084/slavelogs; qsub -N Test-Test2.Suite2-HELLO -w e -notify -m n -cwd -b y -v DISPLAY -o Test-Test2.Suite2-HELLO.log -e Test-Test2.Suite2-HELLO.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105122.20896/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/TargetApp -a hello -l -tp Suite2/Test2 -slave /tmp/geoff/texttest.sge.20Dec105122.20896/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.20Dec105131.26084 -servaddr 10.67.7.36:37573""
->OUT:Your job 8513 ("Test-Test2.Suite2-HELLO") has been submitted
<-SRV:Completed submission of all tests
<-CMD:qdel 8512
->ERR:Somebody has registered the job for deletion
<-CMD:qdel 8513
->ERR:Somebody has registered the job for deletion
