<-SRV:TextTest slave server started on 10.67.7.191:46760
<-CMD:cd /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/grid_core_files; qsub -N Test-Test1.Suite1-HELLO -w e -notify -m n -cwd -b y -v DISPLAY -o /dev/null -e /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/TargetApp -a hello -l -tp Suite1/Test1 -slave /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.27May152123.21434 -servaddr 127.0.0.1:46541""
->OUT:Your job 8512 ("Test-Test1.Suite1-HELLO") has been submitted
<-CMD:cd /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/grid_core_files; qsub -N Test-Test2.Suite2-HELLO -w e -notify -m n -cwd -b y -v DISPLAY -o /dev/null -e /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/TargetApp -a hello -l -tp Suite2/Test2 -slave /tmp/geoff/texttest.sge.gui.27May152122.15240/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.27May152123.21434 -servaddr 127.0.0.1:46541""
->OUT:Your job 8513 ("Test-Test2.Suite2-HELLO") has been submitted
<-SRV:Completed submission of all tests
<-CMD:qdel 8512
->ERR:Somebody has registered the job for deletion
<-CMD:qdel 8513
->ERR:Somebody has registered the job for deletion
