TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff10Jul105727/QueueSystems/GUI/QuitDuringSetup based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application HELLO
Submitting HELLO test-suite TargetApp to SGE queues
  Submitting HELLO test-suite Suite1 to SGE queues
    Submitting HELLO test-case Test1 to default SGE queue
Terminating testing due to external interruption (Interrupted externally)
    Cancelling HELLO test-case Test1 in SGE (job 1)
