TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.08Oct140057/texttest.sge/QueueSystems/ErrorHandling/GUI/QuitDuringSetup based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO
Q: Submitting HELLO test-case Test1 to default SGE queue
Waiting Q thread for 5 seconds
Q: Submitting HELLO test-case Test2 to default SGE queue
Waiting Q thread for 5 seconds
T: Cancelling HELLO test-case Test1 in SGE (job 8512)
T: Cancelling HELLO test-case Test2 in SGE (job 8513)
