TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.13Jun123309/QueueSystems/ErrorHandling/GUI/QuitDuringSetup based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO
Q: Submitting test Test1 to default SGE queue
Q: Submitting test Test2 under Suite1 to default SGE queue
T: Cancelling test Test1 in SGE (job 1)
