TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.29May170107/QueueSystems/ErrorHandling/GUI/QuitDuringSetup based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application HELLO
Submitting HELLO test-suite TargetApp to LSF queues
  Submitting HELLO test-suite Suite1 to LSF queues
    Submitting HELLO test-case Test1 to default LSF queue
    Submitting HELLO test-case Test2 to default LSF queue
    Cancelling HELLO test-case Test1 in LSF (job 1)
