<-SRV:TextTest slave server started on 192.168.99.117:53041
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.13Jan100402.23929/texttest.sge/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.13Jan100412.27087/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Test1.Suite1-HELLO -w e -notify -m n -cwd -b y -V -o Test-Test1.Suite1-HELLO.log -e Test-Test1.Suite1-HELLO.errors 'exec $SHELL -c "exec /carm/proj/texttest/release/current/bin/texttest -d /carm/proj/texttest-tmp/geoff/texttest.13Jan100402.23929/texttest.sge/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/TargetApp -a hello -l -tp Suite1/Test1 -slave /carm/proj/texttest-tmp/geoff/texttest.13Jan100402.23929/texttest.sge/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.13Jan100412.27087 -servaddr 192.168.99.117:53035"'
->OUT:Your job 8512 ("Test-Test1.Suite1-HELLO") has been submitted
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.13Jan100402.23929/texttest.sge/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.13Jan100412.27087/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Test2.Suite2-HELLO -w e -notify -m n -cwd -b y -V -o Test-Test2.Suite2-HELLO.log -e Test-Test2.Suite2-HELLO.errors 'exec $SHELL -c "exec /carm/proj/texttest/release/current/bin/texttest -d /carm/proj/texttest-tmp/geoff/texttest.13Jan100402.23929/texttest.sge/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/TargetApp -a hello -l -tp Suite2/Test2 -slave /carm/proj/texttest-tmp/geoff/texttest.13Jan100402.23929/texttest.sge/QueueSystems/ErrorHandling/GUI/QuitDuringSetup/texttesttmp/console.13Jan100412.27087 -servaddr 192.168.99.117:53035"'
->OUT:Your job 8513 ("Test-Test2.Suite2-HELLO") has been submitted
<-SRV:Completed submission of all tests
<-CMD:qdel 8512
->ERR:Somebody has registered the job for deletion
<-CMD:qdel 8513
->ERR:Somebody has registered the job for deletion
