TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.30Nov175319/QueueSystems/NormalOperation/Console/BatchTestNotInParent based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic3 to default SGE queue
  SLEEP test-case Basic3 FAILED on tiptonville : new results in errors,output
At 17:55 creating batch report for application SLEEP ...file written.
