TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/ErrorHandling/LsfOnly/BadResourceUsage based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/ErrorHandling/LsfOnly/BadResourceUsage/logging
Using LSF queues for Application SLEEP, version badresusage
Q: Submitting SLEEP.badresusage test-case Basic to default LSF queue
S: SLEEP.badresusage test-case Basic not compared:
Failed to submit to LSF (Bad resource requirement syntax. Job not submitted.)
Submission command was 'bsub -J Test-Basic-SLEEP.badresusage -R rusage[no_such_resource=0] -u nobody -o Test-Basic-SLEEP.badresusage.log -e Test-Basic-SLEEP.badresusage.errors ... '

