TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/LsfOnly/BadResourceUsage based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version badresusage
Q: Submitting test Basic to default LSF queue
S: Test Basic not compared:
Failed to submit to LSF (Bad resource requirement syntax. Job not submitted.)
Submission command was 'bsub -J Test-Basic-SLEEP.badresusage -R rusage[no_such_resource=0] -u nobody -o Test-Basic-SLEEP.badresusage.log -e Test-Basic-SLEEP.badresusage.errors ... '

