TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff22Sep141218/QueueSystems/Console/BadQueue based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badqueue, checkout /users/geoff/texttesttmp/texttest.sgegeoff22Sep141218/QueueSystems/Console/BadQueue/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to SGE queue non_existent
  Evaluating SLEEP test-case Basic  (unrunnable)
  SLEEP test-case Basic  not compared:  Failed to submit to SGE (Unable to run job: Job was rejected because job requests unknown queue "non_existent".)
  Submitting SLEEP test-case Basic2 to SGE queue non_existent
  Evaluating SLEEP test-case Basic2 (unrunnable)
  SLEEP test-case Basic2 not compared:  Failed to submit to SGE (Unable to run job: Job was rejected because job requests unknown queue "non_existent".)
