#!/bin/sh
# Usage: RunTest binary runext options

for c in $TEST_CONFIG_FILES; do
  if [ -f "$c" ]; then
    #invoke config script
    . $c
  else 
    echo "ERROR: config script not found, cannot configure $c"
  fi
done

#run the test
TEST_BINARY=$1
TEST_FILE_EXTENSION=$2
export TEST_FILE_EXTENSION
shift 2

#debug: print some environment
#env
#echo $LD_LIBRARY_PATH

if [ -f "$TEST_BINARY" ]; then
    $TEST_BINARY $*
else 
    echo "ERROR: binary not found, cannot run $TEST_BINARY"
fi
