<-SRV:TextTest slave server started on 10.80.17.109:54842
<-CMD:cd /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/JobDeletionFails/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v DISPLAY,STANDARD -o /dev/null -e /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/JobDeletionFails/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/JobDeletionFails/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/JobDeletionFails/texttesttmp/sleep.killing.17Sep112817.2362 -servaddr 127.0.0.1:39134""
->OUT:Your job 1 ("stupid") has been submitted.
<-SRV:Completed submission of all tests
->CLI:30897
sleep.killing:Basic
(itexttestlib.default
Running
p1
(dp2
S'category'
p3
S'running'
p4
sS'freeText'
p5
S'Running on forestville'
p6
sS'started'
p7
I1
sS'completed'
p8
I0
sS'briefText'
p9
S'RUN (forestville)'
p10
sS'executionHosts'
p11
(lp12
S'forestville'
p13
asS'lifecycleChange'
p14
S'start'
p15
sb.
<-CMD:qdel 1
->ERR:Somebody has registered the job for deletion
<-CMD:qdel 1
->ERR:denied: job "1" does not exist
