TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.11Oct155536/texttest.sge/QueueSystems/ErrorHandling/GUI/JobDeletionFails based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default SGE queue
T: Cancelling SLEEP.killing test-case Basic in SGE (job 1)
T: Cancelling SLEEP.killing test-case Basic in SGE (job 1)
