TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/GUI/JobDeletionFails based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/GUI/JobDeletionFails/logging
Using SGE queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default SGE queue
T: Cancelling SLEEP.killing test-case Basic in SGE (job 1)
T: Cancelling SLEEP.killing test-case Basic in SGE (job 1)
