TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/NormalOperation/LsfOnly/NumericResourceRequest based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/NormalOperation/LsfOnly/NumericResourceRequest/logging
Using LSF queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default LSF queue
S: SLEEP test-case Basic succeeded on forestville
