TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff05Apr175134/QueueSystems/Console/Batch2Tests based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /nfs/vm/texttest/central_texttesttmp/texttest.sgegeoff05Apr175134/QueueSystems/Console/Batch2Tests/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  Submitting SLEEP test-case Basic2 to default SGE queue
  Reading slave results for SLEEP test-case Basic  - SUCCESS! (on errors.sleep,output.sleep)
  Reading slave results for SLEEP test-case Basic2 (on errors.sleep,output.sleep)
  SLEEP test-case Basic2 on waterville : new results in errors,output
At 17:53 creating batch report for application SLEEP ...file written
