import_config_file:$STANDARD
import_config_file:capturemock_config

config_module:queuesystem

queue_system_module:SGE

create_catalogues:true
partial_copy_test_path:nonsense

performance_test_machine:any

dbtext_database_path:mongodata
