TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct110224/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillReusedTest based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct110224/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillReusedTest/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
T: Cancelling HELLO test-case Test in SGE (job 25617)
