The following new files/directories were created:
<Test Directory>
----slave
----texttesttmp
--------tdat.env.searchpath.queuesystemgeoff03Jul103417
------------Test2
----------------catalogue.tdat
----------------errors.tdat
----------------my_personal_file
----------------output.tdat
----------------readonlyfile
----------------framework_tmp
--------------------cmd
--------------------slaveerrs
--------------------slavelog
--------------------teststate
--------------------unixperf
