TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff03Jul103722/TestSelf/TestData/Console/SearchPathFromEnv based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application TDAT, version env.searchpath.queuesystem, checkout /users/geoff/texttesttmp/texttest.lsfgeoff03Jul103722/TestSelf/TestData/Console/SearchPathFromEnv/TargetApp
Submitting TDAT test-suite TargetApp to LSF queues
  Submitting TDAT test-case Test2 to default LSF queue
  Evaluating TDAT test-case Test2 (on catalogue.tdat,errors.tdat,output.tdat)
  TDAT test-case Test2 FAILED on quaqtaq : differences in output
  View details(v), Save Version env.searchpath.queuesystem(1), Save Version env.searchpath(2), Save Version env.queuesystem(3), Save Version env(4), Save Version searchpath.queuesystem(5), Save Version searchpath(6), Save Version queuesystem(7), Save(s) or continue(any other key)?
------------------ Differences in output --------------------
2a3
> Got environment variable /users/geoff/texttesttmp/texttest.lsfgeoff03Jul103722/TestSelf/TestData/Console/SearchPathFromEnv/texttesttmp/tdat.env.searchpath.queuesystemgeoff03Jul104336/Test2/my_personal_file
<See also tkdiff window for details of output>
  Save Version env.searchpath.queuesystem(1), Save Version env.searchpath(2), Save Version env.queuesystem(3), Save Version env(4), Save Version searchpath.queuesystem(5), Save Version searchpath(6), Save Version queuesystem(7), Save(s) or continue(any other key)?
Killed process 18622 with signal 2
