#!/usr/bin/env python

import os, sys

def getOption(name):
    prevArg = None
    for arg in sys.argv[1:]:
        if prevArg == name:
            return arg
        prevArg = arg

print "Your job 1 (\"stupid\") has been submitted."
outfile = getOption("-o")
errfile = getOption("-e")
# Run the slave locally in the background so it doesn't use a slot...
os.system(sys.argv[-1] + " > " + outfile + " 2> " + errfile + " &")
