TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/TestSelf/UITesting/UnixOnly/OtherAppDefaultConfig based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/TestSelf/UITesting/UnixOnly/OtherAppDefaultConfig/logging
Using SGE queues for Application DISP, version sge
Q: Submitting DISP.sge test-case Test to default SGE queue
S: DISP.sge test-case Test succeeded on pennsville
