TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/TestSelf/UITesting/UnixOnly/OtherAppDefaultConfig based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application DISP, version sge
Q: Submitting DISP.sge test-case Test to default SGE queue
S: DISP.sge test-case Test succeeded on pennsville
