<-SRV:TextTest slave server started on 10.67.7.142:42769
<-CMD:cd /tmp/geoff/texttest.sge.gui.20Dec105156.19016/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.20Dec105157.20940/slavelogs; qsub -N Test-Basic-SLEEP -w e -notify -m n -cwd -b y -v DISPLAY -o Test-Basic-SLEEP.log -e Test-Basic-SLEEP.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.gui.20Dec105156.19016/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.gui.20Dec105156.19016/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.20Dec105157.20940 -servaddr 10.67.7.142:51897""
->OUT:Your job 7480 ("Test-Basic-SLEEP") has been submitted
<-CMD:cd /tmp/geoff/texttest.sge.gui.20Dec105156.19016/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.20Dec105157.20940/slavelogs; qsub -N Test-Basic2-SLEEP -w e -notify -m n -cwd -b y -v DISPLAY -o Test-Basic2-SLEEP.log -e Test-Basic2-SLEEP.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.gui.20Dec105156.19016/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.sge.gui.20Dec105156.19016/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.20Dec105157.20940 -servaddr 10.67.7.142:51897""
->OUT:Your job 7481 ("Test-Basic2-SLEEP") has been submitted
<-SRV:Completed submission of all tests
<-CMD:qdel 7481
->OUT:geoff has registered the job 7481 for deletion
<-CMD:qdel 7480
->OUT:geoff has registered the job 7480 for deletion
