TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.01Jun095041/QueueSystems/NormalOperation/GUI/KillPending based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to LSF queues
  Submitting SLEEP test-case Basic  to default LSF queue
  Submitting SLEEP test-case Basic2 to default LSF queue
  Cancelling SLEEP test-case Basic2 in LSF (job 7481)
  Cancelling SLEEP test-case Basic  in LSF (job 7480)
