TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.28May091212/QueueSystems/NormalOperation/GUI/KillTests based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  Submitting SLEEP test-case Basic2 to default SGE queue
  Cancelling SLEEP test-case Basic  in SGE (job 3593)
  Cancelling SLEEP test-case Basic2 in SGE (job 3594)
