TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.28May122741/QueueSystems/NormalOperation/GUI/KillTests based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to LSF queues
  Submitting SLEEP test-case Basic  to default LSF queue
  Submitting SLEEP test-case Basic2 to default LSF queue
  Cancelling SLEEP test-case Basic  in LSF (job 7480)
  Cancelling SLEEP test-case Basic2 in LSF (job 7481)
