<-SRV:TextTest slave server started on 192.168.98.14:33111
<-CMD:env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic-SLEEP -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.sge.28May153901/QueueSystems/NormalOperation/GUI/KillPending/TargetApp -a sleep -l -tp Basic -slave /users/geoff/texttesttmp/texttest.sge.28May153901/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/sleep.28May153909 -servaddr 192.168.98.14:33109 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.28May153901/QueueSystems/NormalOperation/GUI/KillPending/slave"'
->OUT:Your job 7480 ("Test-Basic-SLEEP") has been submitted
<-CMD:env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic2-SLEEP -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.sge.28May153901/QueueSystems/NormalOperation/GUI/KillPending/TargetApp -a sleep -l -tp Basic2 -slave /users/geoff/texttesttmp/texttest.sge.28May153901/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/sleep.28May153909 -servaddr 192.168.98.14:33109 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.28May153901/QueueSystems/NormalOperation/GUI/KillPending/slave"'
->OUT:Your job 7481 ("Test-Basic2-SLEEP") has been submitted
<-SRV:Completed submission of all tests
<-CMD:qdel 7480
->OUT:geoff has registered the job 7480 for deletion
<-CMD:qdel 7481
->OUT:geoff has registered the job 7481 for deletion
