<-SRV:TextTest slave server started on 10.67.7.95:39415
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.01Mar115050.19486/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.01Mar115139.3785/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic-SLEEP -w e -notify -m n -cwd -b y -V -o Test-Basic-SLEEP.log -e Test-Basic-SLEEP.errors "exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /carm/proj/texttest-tmp/geoff/texttest.01Mar115050.19486/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/TargetApp -a sleep -l -tp 'Basic' -slave /carm/proj/texttest-tmp/geoff/texttest.01Mar115050.19486/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.01Mar115139.3785 -servaddr 10.67.7.95:41400""
->OUT:Your job 7480 ("Test-Basic-SLEEP") has been submitted
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.01Mar115050.19486/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.01Mar115139.3785/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic2-SLEEP -w e -notify -m n -cwd -b y -V -o Test-Basic2-SLEEP.log -e Test-Basic2-SLEEP.errors "exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /carm/proj/texttest-tmp/geoff/texttest.01Mar115050.19486/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/TargetApp -a sleep -l -tp 'Basic2' -slave /carm/proj/texttest-tmp/geoff/texttest.01Mar115050.19486/texttest.sge.gui/QueueSystems/NormalOperation/GUI/KillPending/texttesttmp/dynamic_gui.01Mar115139.3785 -servaddr 10.67.7.95:41400""
->OUT:Your job 7481 ("Test-Basic2-SLEEP") has been submitted
<-SRV:Completed submission of all tests
<-CMD:qdel 7481
->OUT:geoff has registered the job 7481 for deletion
<-CMD:qdel 7480
->OUT:geoff has registered the job 7480 for deletion
