#!/usr/bin/env python

import sys

def getOption(name):
    prevArg = None
    for arg in sys.argv[1:]:
        if prevArg == name:
            return arg
        prevArg = arg

output = """real 7.02
user 3.5
sys 1.5
"""

perfFile = getOption("-o")
targetFile = open(perfFile, "w")
targetFile.write(output)
