TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff06Sep123217/QueueSystems/Console/CpuLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing3, checkout /users/geoff/texttesttmp/texttest.sgegeoff06Sep123217/QueueSystems/Console/CpuLimit/TargetApp/./
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Reading slave results for SLEEP test-case Basic (killed)
  SLEEP test-case Basic not compared:  Test exceeded queue system's maximum cpu time allowed
At 12:33 creating batch report for application SLEEP ...file written
