TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/CpuLimit based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing3.cpulimit, checkout /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/CpuLimit/TargetApp/
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Evaluating SLEEP test-case Basic (on errors.sleep,output.sleep.cpulimit)
  SLEEP test-case Basic were terminated before completion (CPULIMIT) on gatesville : differences in output
At 17:35 creating batch report for application SLEEP ...file written
