TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.04Jul143732/QueueSystems/SlaveReuse/Slave/AddApplication based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application HELLO, version 1, checkout /users/geoff/texttesttmp/texttest.sge.04Jul143732/QueueSystems/SlaveReuse/Slave/AddApplication/TargetApp/
Running HELLO test-suite TargetApp
  Running HELLO test-case Test
Comparing differences for HELLO test-suite TargetApp
  Comparing differences for HELLO test-case Test (on errors.hello,output.hello)
Using Application HELLO, version 2, checkout /users/geoff/texttesttmp/texttest.sge.04Jul143732/QueueSystems/SlaveReuse/Slave/AddApplication/TargetApp/
Running HELLO test-suite TargetApp
  Running HELLO test-suite Suite
    Running HELLO test-case Test
Comparing differences for HELLO test-suite TargetApp
  Comparing differences for HELLO test-suite Suite
    Comparing differences for HELLO test-case Test - SUCCESS! (on errors.hello,output.hello)
