TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.27Jun114228/QueueSystems/ErrorHandling/Console/OtherAppDefaultConfig based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application HELLO
Q: Submitting test Test to default LSF queue
S: Test Test FAILED on forestville : differences in output
View details(v), Save(s) or continue(any other key)?
