TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.27Jun114106/QueueSystems/ErrorHandling/Console/OtherAppDefaultConfig based on file at /users/geoff/work/master/Testing/Automatic/texttest/QueueSystems/ErrorHandling/Console/OtherAppDefaultConfig/logging.texttest
Using SGE queues for Application HELLO
Q: Submitting test Test to default SGE queue
S: Test Test FAILED on watsonville : differences in output
View details(v), Save(s) or continue(any other key)?
