<-CMD:bhosts -w -R performance_resource
->OUT:HOST_NAME          STATUS          JL/U    MAX  NJOBS    RUN  SSUSP  USUSP    RSV 
perf_machine1.carmen.se ok                 -      2      0      0      0      0      0
perf_machine2.carmen.se ok                 -      2      0      0      0      0      0
bagotville.carmen.se    ok                 -      2      0      0      0      0      0
batesville.carmen.se    ok                 -      2      0      0      0      0      0
bellville.carmen.se     ok                 -      2      0      0      0      0      0
