<-CMD:env 'QUEUE_SYSTEM_RESOURCE=' 'USECASE_RECORD_SCRIPT=/users/geoff/texttesttmp/texttest.lsfgeoff21Aug115554/QueueSystems/Performance/CheckExecHost/NoPerfParallel/texttesttmp/perf.resourcegeoff21Aug115733/Failures/usecase.perf' 'QUEUE_SYSTEM_SUBMIT_ARGS=$TARGET_QS_SUBMIT_ARG' 'USECASE_RECORD_STDIN=/users/geoff/texttesttmp/texttest.lsfgeoff21Aug115554/QueueSystems/Performance/CheckExecHost/NoPerfParallel/texttesttmp/perf.resourcegeoff21Aug115733/Failures/input.perf' 'TEXTTEST_CHECKOUT=' 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff21Aug115554/QueueSystems/Performance/CheckExecHost/NoPerfParallel/texttesttmp/perf.resourcegeoff21Aug115733/Failures:$PATH' 'TEXTTEST_CHECKOUT_NAME=' bhosts -w -R performance_resource
->OUT:HOST_NAME          STATUS          JL/U    MAX  NJOBS    RUN  SSUSP  USUSP    RSV 
perf_machine1.carmen.se ok                 -      2      0      0      0      0      0
perf_machine2.carmen.se ok                 -      2      0      0      0      0      0
bagotville.carmen.se    ok                 -      2      0      0      0      0      0
batesville.carmen.se    ok                 -      2      0      0      0      0      0
bellville.carmen.se     ok                 -      2      0      0      0      0      0
