#!/usr/bin/env python

import os, sys
os.environ["LSB_HOSTS"] = "fake_machine1.carmen.se"
print "Job <1> is submitted to queue <fake_machine_queue>."
# Run the slave locally in the background
os.system("( sleep 5; " + sys.argv[-1] + " ) > /dev/null 2>&1 &")
