TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff30Jun124625/QueueSystems/GUI/ViewPending based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, checkout /users/geoff/texttesttmp/texttest.sgegeoff30Jun124625/QueueSystems/GUI/ViewPending/TargetApp
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic2 to default SGE queue
  Evaluating SLEEP test-case Basic2 (on errors.sleep,output.sleep)
