TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff10Jul105727/QueueSystems/GUI/ViewPending based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Evaluating SLEEP test-case Basic - SUCCESS! (on errors.sleep,output.sleep)
