<-SRV:TextTest slave server started on 10.67.7.36:34135
<-CMD:cd /tmp/geoff/texttest.sge.gui.20Dec105157.28145/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitDuringRead/texttesttmp/dynamic_gui.20Dec105201.30124/slavelogs; qsub -N Test-Basic-SLEEP -w e -notify -m n -cwd -b y -v DISPLAY -o Test-Basic-SLEEP.log -e Test-Basic-SLEEP.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.gui.20Dec105157.28145/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitDuringRead/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.gui.20Dec105157.28145/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitDuringRead/texttesttmp/dynamic_gui.20Dec105201.30124 -servaddr 10.67.7.36:47667""
->OUT:Your job 7480 ("Test-Basic-SLEEP") has been submitted
<-CMD:qdel 7480
->OUT:geoff has registered the job 7480 for deletion
<-SRV:Completed submission of all tests
