<-SRV:TextTest slave server started on 10.80.17.102:33522
<-CMD:cd /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitDuringRead/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP -w e -notify -m n -cwd -b y -v DISPLAY,STANDARD -o /dev/null -e /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitDuringRead/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitDuringRead/TargetApp -a sleep -l -tp Basic -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitDuringRead/texttesttmp/dynamic_gui.17Sep112813.2727 -servaddr 127.0.0.1:56764""
->OUT:Your job 7480 ("Test-Basic-SLEEP") has been submitted
<-CMD:qdel 7480
->OUT:geoff has registered the job 7480 for deletion
<-SRV:Completed submission of all tests
