<-SRV:TextTest slave server started on 10.67.7.36:45036
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.20878/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/texttesttmp/sleep.killing.20Dec105126.25850/slavelogs; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.20878/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.20878/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/texttesttmp/sleep.killing.20Dec105126.25850 -servaddr 10.67.7.36:45584 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job 1 does not exist
<-CMD:qacct -j 1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.20Dec105121.20878/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/sge/default/common/accounting.0
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.20Dec105121.20878/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/sge/default/common/accounting.1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.20Dec105121.20878/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/sge/default/common/accounting.2
->OUT:This job ran several days ago!
