<-SRV:TextTest slave server started on 10.67.6.149:53418
<-CMD:cd /tmp/geoff/texttest.sge.signals.27May152111.118848/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.signals.27May152111.118848/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.signals.27May152111.118848/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.signals.27May152111.118848/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/texttesttmp/sleep.killing.27May152113.1478 -servaddr 127.0.0.1:40404 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job 1 does not exist
<-CMD:qacct -j 1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.signals.27May152111.118848/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/sge/default/common/accounting.0
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.signals.27May152111.118848/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/sge/default/common/accounting.1
->ERR:error: job id 1 not found
<-CMD:qacct -j 1 -f /tmp/geoff/texttest.sge.signals.27May152111.118848/texttest.sge.signals/QueueSystems/ErrorHandling/SgeOnly/Killing/JobInOldAcctFile/sge/default/common/accounting.2
->OUT:This job ran several days ago!
