TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.21Aug150852.21171/texttest.lsf/QueueSystems/ErrorHandling/LsfOnly/LsfMessages based on file at /carm/proj/texttest-tmp/geoff/texttest.21Aug150852.21171/texttest.lsf/QueueSystems/ErrorHandling/LsfOnly/LsfMessages/logging
Using LSF queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default LSF queue
Unexpected output from bsub : Today LSF is feeling talkative
S: SLEEP test-case Basic succeeded on dolgeville
