Using SGE queues for Application HELLO, checkout /tmp/geoff/texttest.25May172628.556/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/VirtualDisplayArgs/TargetApp/
Using SGE queues for Application HELLO, version virtdisp, checkout /tmp/geoff/texttest.25May172628.556/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/VirtualDisplayArgs/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on kilimanjaro : differences in output
View details(v), Approve(a) or continue(any other key)?
Q: Submitting HELLO.virtdisp test-case Test to default SGE queue
S: HELLO.virtdisp test-case Test FAILED on kilimanjaro : differences in output
View details(v), Approve Version virtdisp(1), Approve(a) or continue(any other key)?
