TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.30Nov175319/TestSelf/TestData/UnixOnly/PartialCopyIgnoreCatalogues based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application TDAT, version queuesystem
Submitting TDAT test-suite TargetApp to SGE queues
  Submitting TDAT test-case Test1 to default SGE queue
  TDAT test-case Test1 succeeded on statesville
