TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff10Jul105727/TestSelf/TestData/UnixOnly/PartialCopyIgnoreCatalogues based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application TDAT, version queuesystem
Submitting TDAT test-suite TargetApp to SGE queues
  Submitting TDAT test-case Test1 to default SGE queue
  Evaluating TDAT test-case Test1 - SUCCESS! (on catalogue.tdat,errors.tdat,output.tdat)
