<-SRV:TextTest slave server started on 10.67.7.142:41865
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; bsub -J Test-Basic-SLEEP.badresource -R "no_such_resource " -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.20Dec105135.18121 -servaddr 10.67.7.142:38589""
->ERR:Bad resource requirement syntax. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; bsub -J Test-Basic2-SLEEP.badresource -R "no_such_resource " -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105121.15200/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.20Dec105135.18121 -servaddr 10.67.7.142:38589""
->ERR:Bad resource requirement syntax. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
