<-SRV:TextTest slave server started on 10.67.7.143:55752
<-CMD:cd /tmp/geoff/texttest.lsf.27May152122.26631/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; bsub -J Test-Basic-SLEEP.badresource -R "no_such_resource " -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152122.26631/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic -slave /tmp/geoff/texttest.lsf.27May152122.26631/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.27May152124.29316 -servaddr 127.0.0.1:36188""
->ERR:Bad resource requirement syntax. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.lsf.27May152122.26631/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; bsub -J Test-Basic2-SLEEP.badresource -R "no_such_resource " -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152122.26631/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic2 -slave /tmp/geoff/texttest.lsf.27May152122.26631/texttest.lsf/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.27May152124.29316 -servaddr 127.0.0.1:36188""
->ERR:Bad resource requirement syntax. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
