<-SRV:TextTest slave server started on 10.67.7.147:43634
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92858/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92858/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic -slave /tmp/geoff/texttest.sge.04Mar153053.92858/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.04Mar153056.98148 -servaddr 10.67.7.147:42896""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92858/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92858/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic2 -slave /tmp/geoff/texttest.sge.04Mar153053.92858/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.04Mar153056.98148 -servaddr 10.67.7.147:42896""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
