<-SRV:TextTest slave server started on 10.67.7.36:41129
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic -slave /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.27May152110.16443 -servaddr 127.0.0.1:40985""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic2 -slave /tmp/geoff/texttest.sge.27May152109.11167/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.27May152110.16443 -servaddr 127.0.0.1:40985""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
