<-SRV:TextTest slave server started on 10.67.7.146:56829
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.20628/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.20Dec105140.25721/slavelogs; qsub -N Test-Basic-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.badresource.log -e Test-Basic-SLEEP.badresource.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.20628/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105139.20628/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.20Dec105140.25721 -servaddr 10.67.7.146:43537""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.20628/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.20Dec105140.25721/slavelogs; qsub -N Test-Basic2-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -o Test-Basic2-SLEEP.badresource.log -e Test-Basic2-SLEEP.badresource.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.20628/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep.badresource -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105139.20628/texttest.sge/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/console.badresource.20Dec105140.25721 -servaddr 10.67.7.146:43537""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
