<-SRV:TextTest slave server started on 192.168.99.38:37483
<-CMD:qsub -N Test-Basic-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest -d /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep -v badresource -l -tp Basic -slave /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/sleep.badresource.16Feb112314 -servaddr 192.168.99.38:37481 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadResource/slave"'
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:qsub -N Test-Basic2-SLEEP.badresource -l no_such_resource -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest -d /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadResource/TargetApp -a sleep -v badresource -l -tp Basic2 -slave /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadResource/texttesttmp/sleep.badresource.16Feb112314 -servaddr 192.168.99.38:37481 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadResource/slave"'
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
