TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.26Jun085941/QueueSystems/NormalOperation/Console/NoEnvironment based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO
Q: Submitting test Test to default SGE queue
S: Test Test FAILED on schefferville : differences in output
View details(v), Save(s) or continue(any other key)?
