TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/NormalOperation/Console/KeepInfoInSlave based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/NormalOperation/Console/KeepInfoInSlave/logging
Using Application SLEEP, version startdigit
Running SLEEP.startdigit test-suite TargetApp
  Running SLEEP.startdigit test-case 123Test
Comparing differences for SLEEP.startdigit test-suite TargetApp
  Comparing differences for SLEEP.startdigit test-case 123Test - SUCCESS! (on errors.sleep,output.sleep)
