TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.15Oct142840/texttest.sge/QueueSystems/NormalOperation/Console/KeepInfoInSlave based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version startdigit
Running SLEEP.startdigit test-suite TargetApp
  Running SLEEP.startdigit test-case 123Test
Comparing differences for SLEEP.startdigit test-suite TargetApp
  Comparing differences for SLEEP.startdigit test-case 123Test - SUCCESS! (on errors.sleep,output.sleep)
