<-SRV:TextTest slave server started on 10.67.7.148:60377
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.63317/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/console.badperfmachine.20Dec105141.68284/slavelogs; qsub -N Test-Basic-SLEEP.badperfmachine -l hostname=no_such_machine|no_such_machine2 -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.badperfmachine.log -e Test-Basic-SLEEP.badperfmachine.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.63317/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/TargetApp -a sleep.badperfmachine -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105139.63317/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/console.badperfmachine.20Dec105141.68284 -servaddr 10.67.7.148:43654""
->ERR:Unable to run job: can't resolve hostname "no_such_machine|no_such_machine2".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.63317/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/console.badperfmachine.20Dec105141.68284/slavelogs; qsub -N Test-Basic2-SLEEP.badperfmachine -l hostname=no_such_machine|no_such_machine2 -w e -notify -m n -cwd -b y -o Test-Basic2-SLEEP.badperfmachine.log -e Test-Basic2-SLEEP.badperfmachine.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.63317/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/TargetApp -a sleep.badperfmachine -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105139.63317/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/console.badperfmachine.20Dec105141.68284 -servaddr 10.67.7.148:43654""
->ERR:Unable to run job: can't resolve hostname "no_such_machine|no_such_machine2".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
