<-SRV:TextTest slave server started on 10.67.7.147:60468
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92855/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.badperfmachine -l hostname=no_such_machine|no_such_machine2 -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92855/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/TargetApp -a sleep.badperfmachine -l -tp Basic -slave /tmp/geoff/texttest.sge.04Mar153053.92855/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/console.badperfmachine.04Mar153056.98151 -servaddr 10.67.7.147:41118""
->ERR:Unable to run job: can't resolve hostname "no_such_machine|no_such_machine2".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92855/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.badperfmachine -l hostname=no_such_machine|no_such_machine2 -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92855/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/TargetApp -a sleep.badperfmachine -l -tp Basic2 -slave /tmp/geoff/texttest.sge.04Mar153053.92855/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceMachine/texttesttmp/console.badperfmachine.04Mar153056.98151 -servaddr 10.67.7.147:41118""
->ERR:Unable to run job: can't resolve hostname "no_such_machine|no_such_machine2".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
