<-SRV:TextTest slave server started on 10.67.7.142:57513
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; bsub -J Test-Basic-SLEEP.badqueue -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.20Dec105135.18114 -servaddr 10.67.7.142:52573""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; bsub -J Test-Basic2-SLEEP.badqueue -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105121.15228/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.20Dec105135.18114 -servaddr 10.67.7.142:52573""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
