<-SRV:TextTest slave server started on 10.67.7.138:44241
<-CMD:cd /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.badqueue -q non_existent -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic -slave /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.27May152109.8626 -servaddr 127.0.0.1:35550""
->ERR:
Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.badqueue -q non_existent -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic2 -slave /tmp/geoff/texttest.sge.27May152108.4714/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.27May152109.8626 -servaddr 127.0.0.1:35550""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
