<-SRV:TextTest slave server started on 10.67.7.191:48410
<-CMD:cd /tmp/geoff/texttest.lsf.27May152123.16551/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; bsub -J Test-Basic-SLEEP.badqueue -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152123.16551/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic -slave /tmp/geoff/texttest.lsf.27May152123.16551/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.27May152125.21566 -servaddr 127.0.0.1:44580""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.lsf.27May152123.16551/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; bsub -J Test-Basic2-SLEEP.badqueue -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152123.16551/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic2 -slave /tmp/geoff/texttest.lsf.27May152123.16551/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.27May152125.21566 -servaddr 127.0.0.1:44580""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
