<-SRV:TextTest slave server started on 10.0.2.100:35973
<-CMD:cd /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.badqueue -q non_existent -w e -notify -m n -cwd -b y -v STANDARD,DISPLAY -o /dev/null -e /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files/slave_start_errors.matlar exec $SHELL -c "exec /home/matlar/work/texttest-devel/local/texttest/bin/texttest -d /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic -slave /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.22Jan143342.2125972 -servaddr 127.0.0.1:47975"
->ERR:
Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:cd /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.badqueue -q non_existent -w e -notify -m n -cwd -b y -v STANDARD,DISPLAY -o /dev/null -e /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/grid_core_files/slave_start_errors.matlar exec $SHELL -c "exec /home/matlar/work/texttest-devel/local/texttest/bin/texttest -d /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep.badqueue -l -tp Basic2 -slave /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/console.badqueue.22Jan143342.2125972 -servaddr 127.0.0.1:47975"
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
