<-SRV:TextTest slave server started on 192.168.99.32:42449
<-CMD:qsub -N Test-Basic-SLEEP.badqueue -q non_existent -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest -d /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep -v badqueue -l -tp Basic -slave /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/sleep.badqueue.16Feb112313 -servaddr 192.168.99.32:42447 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadQueue/slave"'
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:qsub -N Test-Basic2-SLEEP.badqueue -q non_existent -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest -d /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadQueue/TargetApp -a sleep -v badqueue -l -tp Basic2 -slave /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadQueue/texttesttmp/sleep.badqueue.16Feb112313 -servaddr 192.168.99.32:42447 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadQueue/slave"'
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
