<-SRV:TextTest slave server started on 10.67.7.36:60985
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP -l hostname=no_such_machine -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/texttesttmp/console.27May152110.16455 -servaddr 127.0.0.1:59904""
->ERR:Unable to run job: can't resolve hostname "no_such_machine".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP -l hostname=no_such_machine -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.sge.27May152109.11381/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/BadRunMachineLocal/texttesttmp/console.27May152110.16455 -servaddr 127.0.0.1:59904""
->ERR:Unable to run job: can't resolve hostname "no_such_machine".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
