<-SRV:TextTest slave server started on 10.67.7.146:54979
<-CMD:cd /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP -w e -notify -m n -cwd -b y -v DISPLAY -o /dev/null -e /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/texttesttmp/dynamic_gui.27May152107.36086 -servaddr 127.0.0.1:40951""
->OUT:Your job 7480 ("Test-Basic-SLEEP") has been submitted
<-CMD:cd /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP -w e -notify -m n -cwd -b y -v DISPLAY -o /dev/null -e /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.sge.27May152103.32556/texttest.sge.gui/QueueSystems/NormalOperation/GUI/QuitWithPending/texttesttmp/dynamic_gui.27May152107.36086 -servaddr 127.0.0.1:40951""
->OUT:Your job 7481 ("Test-Basic2-SLEEP") has been submitted
<-SRV:Completed submission of all tests
<-CMD:qdel 7480
->OUT:geoff has registered the job 7480 for deletion
<-CMD:qdel 7481
->OUT:geoff has registered the job 7481 for deletion
