<-SRV:TextTest slave server started on 10.67.7.38:52576
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/grid_core_files; qsub -N Test-Test-HELLO -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello -l -tp Test -slave /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.20Dec105129.10800 -servaddr 10.67.7.38:57887""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/grid_core_files; qsub -N Test-Test-HELLO2 -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello2 -l -tp Test -slave /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.20Dec105129.10800 -servaddr 10.67.7.38:57887""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/grid_core_files; qsub -N Test-Test_copy-HELLO2 -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello2 -l -tp Test_copy -slave /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.20Dec105129.10800 -servaddr 10.67.7.38:57887""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/grid_core_files; qsub -N Test-Test_copy-HELLO -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello -l -tp Test_copy -slave /tmp/geoff/texttest.sge.20Dec105124.9012/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.20Dec105129.10800 -servaddr 10.67.7.38:57887""
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
