<-SRV:TextTest slave server started on 10.67.20.109:50851
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506/slavelogs; qsub -N Test-Test-HELLO -l no_such_resource -w e -notify -m n -cwd -b y -V -o Test-Test-HELLO.log -e Test-Test-HELLO.errors 'exec $SHELL -c "exec /carm/proj/texttest/release/current/site/bin/texttest -d /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello -l -tp Test -slave /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506 -servaddr 10.67.20.109:53354"'
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506/slavelogs; qsub -N Test-Test-HELLO2 -l no_such_resource -w e -notify -m n -cwd -b y -V -o Test-Test-HELLO2.log -e Test-Test-HELLO2.errors 'exec $SHELL -c "exec /carm/proj/texttest/release/current/site/bin/texttest -d /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello2 -l -tp Test -slave /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506 -servaddr 10.67.20.109:53354"'
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506/slavelogs; qsub -N Test-Test_copy-HELLO2 -l no_such_resource -w e -notify -m n -cwd -b y -V -o Test-Test_copy-HELLO2.log -e Test-Test_copy-HELLO2.errors 'exec $SHELL -c "exec /carm/proj/texttest/release/current/site/bin/texttest -d /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello2 -l -tp Test_copy -slave /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506 -servaddr 10.67.20.109:53354"'
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506/slavelogs; qsub -N Test-Test_copy-HELLO -l no_such_resource -w e -notify -m n -cwd -b y -V -o Test-Test_copy-HELLO.log -e Test-Test_copy-HELLO.errors 'exec $SHELL -c "exec /carm/proj/texttest/release/current/site/bin/texttest -d /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/TargetApp -a hello -l -tp Test_copy -slave /carm/proj/texttest-tmp/geoff/texttest.06Aug172608.31500/texttest.sge/QueueSystems/NormalOperation/Console/InterleaveTests/texttesttmp/console.06Aug172611.31506 -servaddr 10.67.20.109:53354"'
->ERR:Unable to run job: unknown resource "no_such_resource".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
