TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.29Jun163836/QueueSystems/SlaveReuse/MasterReuseSlave based on file at /users/geoff/work/master/Testing/Automatic/texttest/QueueSystems/SlaveReuse/MasterReuseSlave/logging.texttest
Using SGE queues for Application HELLO
Q: Submitting test Test under TargetApp to default SGE queue
Waiting Q thread for 5 seconds
S: Test Test under TargetApp FAILED on tiptonville : differences in output
View details(v), Save(s) or continue(any other key)?
S: Test Test under Suite succeeded on morafenobe
