Using SGE queues for Application HELLO, checkout /home/geoff/.texttest/tmp/dynamic_gui.1_from_03apr174421.64155/texttest.sge/QueueSystems/SlaveReuse/Master/AllowRacing/BasicReuse/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
Waiting Q thread for 5 seconds
S: HELLO test-case Test FAILED on tiptonville : differences in output
View details(v), Approve(a) or continue(any other key)?
S: HELLO test-case Suite/Test succeeded on morafenobe
