Using SGE queues for Application HELLO, checkout /tmp/geoff/texttest.25May170920.15059/texttest.sge/QueueSystems/SlaveReuse/Master/AllowRacing/BasicReuse/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
Waiting Q thread for 5 seconds
S: HELLO test-case Test FAILED on tiptonville : differences in output
View details(v), Approve(a) or continue(any other key)?
S: HELLO test-case Test succeeded on morafenobe
