TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct105542/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/CancelBeyondCapacity based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct105542/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/CancelBeyondCapacity/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling HELLO test-case Test in SGE (job 9019)
S: HELLO test-case Test not compared:  Test job was cancelled (while still pending in SGE) at 10:55
S: HELLO test-case Test not compared:  Test run was cancelled before it had started
At 10:55 creating batch report for application HELLO ...
Sending mail from address geoff@localhost to ['geoff@localhost']
done.
