#!/usr/bin/env python
import os
if os.getenv("TEXTTEST_FAKE_MACHINE").find("machine1") != -1:
    print """4 S root      3171     1  0  78   0 -   545 -      Apr19 tty5     00:00:00 /sbin/mingetty tty5
4 S root      3172     1  0  78   0 -   388 -      Apr19 tty6     00:00:00 /sbin/mingetty tty6
0 S fakeuser  fake_xvfb_server     1  0  76   0 -  4211 -      Apr00 ?        00:40:35 Xvfb :42
0 S geoff     3991     1  0  76   0 -  1308 -      Apr19 ?        00:00:01 xclock -display fougamou:42.0
0 S curt     31179     1  0  76   0 -  1654 -      Apr19 ?        00:00:00 /usr/libexec/gconfd-2 10
0 S mattias   4643     1  0  76   0 -  1302 -      Apr27 ?        00:00:01 xclock -display fougamou:42.0
4 S sgeadmin 14579  3083  0  78   0 -   742 wait   Apr27 ?        00:00:00 sge_shepherd-3538872 -bg"""
