#!/usr/bin/env python

import os, time, signal, sys

if ":3" in sys.argv:
    os.kill(os.getppid(), signal.SIGUSR1)
    signal.pause()
else:
    sys.stderr.write("""
Fatal server error:
Could not create server lock file: /tmp/.X3979-lock
""")

    
