TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.13Nov141742/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ReuseOnlyBeyondCapacity based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.13Nov141742/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ReuseOnlyBeyondCapacity/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Save(s) or continue(any other key)?
S: HELLO test-case Test succeeded on centreville.carmen.se
