TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct110208/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ReuseOnlyBeyondCapacity based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct110208/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ReuseOnlyBeyondCapacity/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on forestville : differences in output
View details(v), Save(s) or continue(any other key)?
S: HELLO test-case Test succeeded on forestville
