#!/usr/bin/env python

import os, getopt, sys, string

fulldir, local = os.path.split(sys.argv[0])
os.environ["PE_HOSTFILE"] = os.path.join(fulldir, "sgehostfile")
print "Called fake SGE with arguments", string.join(sys.argv[1:-1])
print "Your job 1 (\"stupid\") has been submitted."
# Run the slave locally, but pretend we're in parallel... bin the output
os.system(sys.argv[-1] + " > /dev/null 2>&1")
