Using SGE queues for Application HELLO, version resource, checkout /tmp/geoff/texttest.sge.04Mar153054.104136/texttest.sge/QueueSystems/SlaveReuse/Master/AllowRacing/RespectResources/TargetApp/
Q: Submitting HELLO.resource test-case Test to default SGE queue
Waiting Q thread for 5 seconds
S: HELLO.resource test-case Test FAILED on schellville : differences in output
View details(v), Save Version resource(1), Save(s) or continue(any other key)?
Q: Submitting HELLO.resource test-case Test to default SGE queue
S: HELLO.resource test-case Test not compared:
Failed to submit to SGE (Unable to run job: unknown resource "no_such_resource".)
Submission command was 'qsub -N Test-Test.Suite-HELLO.resource -l no_such_resource -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null ... '

