<-SRV:TextTest slave server started on 10.67.6.149:53277
<-CMD:cd /tmp/geoff/texttest.sge.signals.27May152111.118746/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.signals.27May152111.118746/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.signals.27May152111.118746/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.signals.27May152111.118746/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/sleep.killing.27May152113.1495 -servaddr 127.0.0.1:39572 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:somebody has deleted job 1
