<-SRV:TextTest slave server started on 10.67.7.36:60091
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.20876/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/sleep.killing.20Dec105137.26796/slavelogs; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT bsub -J Test-Basic-SLEEP.killing -u nobody -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.20876/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.20876/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/sleep.killing.20Dec105137.26796 -servaddr 10.67.7.36:40181 -b short_local""
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->OUT:Job <1> is being terminated
