<-SRV:TextTest slave server started on 10.67.7.144:60970
<-CMD:cd /tmp/geoff/texttest.lsf.signals.27May152123.17974/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/grid_core_files; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT bsub -J Test-Basic-SLEEP.killing -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.signals.27May152123.17974/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.lsf.signals.27May152123.17974/texttest.lsf.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/sleep.killing.27May152125.20563 -servaddr 127.0.0.1:57123 -b short_local""
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->OUT:Job <1> is being terminated
