<-SRV:TextTest slave server started on 10.80.17.153:59291
<-CMD:cd /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/grid_core_files/slave_start_errors.ec2-user exec "$SHELL -c "exec /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.17Sep172713.61893/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/sleep.killing.17Sep112811.2146 -servaddr 127.0.0.1:38349 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:somebody has deleted job 1
