<-SRV:TextTest slave server started on 10.67.7.142:44004
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15173/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15173/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/TargetApp -a sleep.killing -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.15173/texttest.sge.signals/QueueSystems/ErrorHandling/Console/Killing/JobStaysPending/texttesttmp/sleep.killing.20Dec105127.17865 -servaddr 10.67.7.142:53214 -b short_local""
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:somebody has deleted job 1
