<-SRV:TextTest slave server started on 10.67.7.147:40980
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92856/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.badperfarch -l arch=no_such_arch -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92856/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfarch -l -tp Basic -slave /tmp/geoff/texttest.sge.04Mar153053.92856/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.04Mar153056.98153 -servaddr 10.67.7.147:43563""
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92856/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.badperfarch -l arch=no_such_arch -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92856/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfarch -l -tp Basic2 -slave /tmp/geoff/texttest.sge.04Mar153053.92856/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.04Mar153056.98153 -servaddr 10.67.7.147:43563""
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
