<-SRV:TextTest slave server started on 10.67.7.146:49547
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.20875/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.20Dec105141.25773/slavelogs; qsub -N Test-Basic-SLEEP.badperfarch -l arch=no_such_arch -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.badperfarch.log -e Test-Basic-SLEEP.badperfarch.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.20875/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfarch -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105139.20875/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.20Dec105141.25773 -servaddr 10.67.7.146:47103""
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.20875/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.20Dec105141.25773/slavelogs; qsub -N Test-Basic2-SLEEP.badperfarch -l arch=no_such_arch -w e -notify -m n -cwd -b y -o Test-Basic2-SLEEP.badperfarch.log -e Test-Basic2-SLEEP.badperfarch.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.20875/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfarch -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105139.20875/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.20Dec105141.25773 -servaddr 10.67.7.146:47103""
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
