<-SRV:TextTest slave server started on 10.67.7.38:37453
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105125.9001/texttest.lsf/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files; bsub -J Test-Basic-SLEEP.badperfmodel -R "model==no_such_model " -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105125.9001/texttest.lsf/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfmodel -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105125.9001/texttest.lsf/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfmodel.20Dec105137.10858 -servaddr 10.67.7.38:57321""
->ERR:Bad resource requirement syntax. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105125.9001/texttest.lsf/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files; bsub -J Test-Basic2-SLEEP.badperfmodel -R "model==no_such_model " -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105125.9001/texttest.lsf/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfmodel -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105125.9001/texttest.lsf/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfmodel.20Dec105137.10858 -servaddr 10.67.7.38:57321""
->ERR:Bad resource requirement syntax. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
