<-SRV:TextTest slave server started on 10.67.7.36:32915
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.badperfarch -l arch=no_such_arch -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfarch -l -tp Basic -slave /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.27May152110.16449 -servaddr 127.0.0.1:35389""
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP.badperfarch -l arch=no_such_arch -w e -notify -m n -cwd -b y -o /dev/null -e /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/grid_core_files/slave_start_errors.geoff exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep.badperfarch -l -tp Basic2 -slave /tmp/geoff/texttest.sge.27May152109.11184/texttest.sge/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/console.badperfarch.27May152110.16449 -servaddr 127.0.0.1:35389""
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
