<-SRV:TextTest slave server started on 192.168.99.31:42815
<-CMD:qsub -N Test-Basic-SLEEP.badperfarch -l "osversion=RHEL4|SOL*|HP*,arch=no_such_arch" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest -d /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep -v badperfarch -l -tp Basic -slave /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/sleep.badperfarch.16Feb112313 -servaddr 192.168.99.31:42813 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadPerformanceModel/slave"'
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
<-CMD:qsub -N Test-Basic2-SLEEP.badperfarch -l "osversion=RHEL4|SOL*|HP*,arch=no_such_arch" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest -d /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadPerformanceModel/TargetApp -a sleep -v badperfarch -l -tp Basic2 -slave /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadPerformanceModel/texttesttmp/sleep.badperfarch.16Feb112313 -servaddr 192.168.99.31:42813 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.16Feb112111/QueueSystems/ErrorHandling/Console/BadPerformanceModel/slave"'
->ERR:Unable to run job: error: no suitable queues.
Exiting.
->EXC:1
