TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct110224/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/CheckoutChange based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct110224/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/CheckoutChange/TargetApp/
Using SGE queues for Application HELLO, version altcheckout, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.26Oct110224/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/CheckoutChange/TargetApp/../
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test succeeded on schellville
S: HELLO.altcheckout test-case Test succeeded on schellville
