Using SGE queues for Application HELLO, checkout /home/geoff/.texttest/tmp/dynamic_gui.1_from_03apr174421.64155/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/CheckoutChange/TargetApp/
Using SGE queues for Application HELLO, version altcheckout
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Suite/Test succeeded on centreville.carmen.se
S: HELLO.altcheckout test-case Suite/Test succeeded on centreville.carmen.se
