<-SRV:TextTest slave server started on 10.67.7.142:57841
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15181/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105135.18116/slavelogs; bsub -J Test-Basic-SLEEP -q non_existent -u nobody -o Test-Basic-SLEEP.log -e Test-Basic-SLEEP.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15181/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105121.15181/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105135.18116 -servaddr 10.67.7.142:33149""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105121.15181/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105135.18116/slavelogs; bsub -J Test-Basic2-SLEEP -q non_existent -u nobody -o Test-Basic2-SLEEP.log -e Test-Basic2-SLEEP.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105121.15181/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105121.15181/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105135.18116 -servaddr 10.67.7.142:33149""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
