<-SRV:TextTest slave server started on 10.67.7.146:41847
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.20592/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105140.25713/slavelogs; qsub -N Test-Basic-SLEEP -q non_existent -w e -notify -m n -cwd -b y -o Test-Basic-SLEEP.log -e Test-Basic-SLEEP.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.20592/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.20Dec105139.20592/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105140.25713 -servaddr 10.67.7.146:55932""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.20Dec105139.20592/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105140.25713/slavelogs; qsub -N Test-Basic2-SLEEP -q non_existent -w e -notify -m n -cwd -b y -o Test-Basic2-SLEEP.log -e Test-Basic2-SLEEP.errors exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.20Dec105139.20592/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.sge.20Dec105139.20592/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.20Dec105140.25713 -servaddr 10.67.7.146:55932""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
