<-SRV:TextTest slave server started on 10.67.7.147:48490
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92876/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP -q non_existent -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92876/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.sge.04Mar153053.92876/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.04Mar153056.98149 -servaddr 10.67.7.147:59098""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:cd /tmp/geoff/texttest.sge.04Mar153053.92876/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/grid_core_files; qsub -N Test-Basic2-SLEEP -q non_existent -w e -notify -m n -cwd -b y -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.sge.04Mar153053.92876/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.sge.04Mar153053.92876/texttest.sge/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.04Mar153056.98149 -servaddr 10.67.7.147:59098""
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
