<-SRV:TextTest slave server started on 10.67.7.143:56905
<-CMD:cd /tmp/geoff/texttest.lsf.27May152122.26614/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/grid_core_files; bsub -J Test-Basic-SLEEP -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152122.26614/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic -slave /tmp/geoff/texttest.lsf.27May152122.26614/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.27May152124.29314 -servaddr 127.0.0.1:60922""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-CMD:cd /tmp/geoff/texttest.lsf.27May152122.26614/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/grid_core_files; bsub -J Test-Basic2-SLEEP -q non_existent -u nobody -o /dev/null -e /dev/null exec "$SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /tmp/geoff/texttest.lsf.27May152122.26614/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic2 -slave /tmp/geoff/texttest.lsf.27May152122.26614/texttest.lsf/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/console.27May152124.29314 -servaddr 127.0.0.1:60922""
->ERR:non_existent: No such queue. Job not submitted.
->EXC:255
<-SRV:Completed submission of all tests
