<-SRV:TextTest slave server started on 192.168.99.66:41929
<-CMD:qsub -N Test-Basic-SLEEP -q non_existent -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.sge.01Jun161725/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic -slave /users/geoff/texttesttmp/texttest.sge.01Jun161725/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/sleep.01Jun161755 -servaddr 192.168.99.66:41927 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.01Jun161725/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/slave"'
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-CMD:qsub -N Test-Basic2-SLEEP -q non_existent -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.sge.01Jun161725/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/TargetApp -a sleep -l -tp Basic2 -slave /users/geoff/texttesttmp/texttest.sge.01Jun161725/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/texttesttmp/sleep.01Jun161755 -servaddr 192.168.99.66:41927 -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.sge.01Jun161725/QueueSystems/ErrorHandling/Console/BadQueueCommandLine/slave"'
->ERR:Unable to run job: Job was rejected because job requests unknown queue "non_existent".
Exiting.
->EXC:1
<-SRV:Completed submission of all tests
