TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/Console/OtherAppDefaultConfig/LocalAndGrid based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/Console/OtherAppDefaultConfig/LocalAndGrid/logging
Using SGE queues for Application HELLO
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on watsonville : differences in output
View details(v), Save(s) or continue(any other key)?
