TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/ErrorHandling/Console/OtherAppDefaultConfig based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on watsonville : differences in output
View details(v), Save(s) or continue(any other key)?
