
---------- Window 'TDAT.env.queuesystem tests (started at 28Nov04:16:45) - TextTest dynamic GUI' ----------
Focus widget is 'Test Tree'

Menu Bar : '_File' (+) , '_View' (+) , '_Actions' (+) , '_Help' (+)

Tool Bar :
  _Quit (Stock image 'gtk-quit', accelerator 'Ctrl+Q', tooltip 'Quit')
  _Kill (Stock image 'gtk-stop', greyed out, accelerator 'Ctrl+Delete', tooltip 'Kill selected tests')
  _Approve (Stock image 'gtk-apply', greyed out, accelerator 'Ctrl+S', tooltip 'Approve results for selected tests. This will save the files produced by this run as the new approved files which future runs will be compared with. Used to be called Save.')
  Progress bar set to fraction 0.0, text 'All 0 tests completed at 28Nov04:16:46'
...........

Showing Test Tree with columns: Tests: All 0 selected , Details

------------------------------ (vertical pane separator)
...........

Showing Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
'Shortcuts:' , Button '_New'
...........
'TextTest started at 28Nov04:16:46.' , Image 'throbber_inactive.png'
----------------------------------------------------------------------------------------------------

Progress bar set to fraction 0.0, text '0 of 1 tests completed'

Column titles changed in Test Tree with columns: Tests: 0/1 selected, all hidden , Details

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box
-> Pending (grey80,bold) | 1 (grey80,bold) | Check box

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box
-> Pending (white) | 0 (white) | Check box
-> Initial filter (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box
-> Pending (white) | 0 (white) | Check box
-> Initial filter (white) | 0 (white) | Check box
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box
-> Pending (white) | 0 (white) | Check box
-> Initial filter (white) | 0 (white) | Check box
-> Running (white) | 0 (white) | Check box
-> Final filter (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box

Progress bar set to fraction 1.0, text 'All 1 tests completed at 28Nov04:16:46'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (tdat.env.queuesystem) (black/white,bold) | (white)
->   Test2 (black/salmon) | output different (salmon)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box
-> Pending (white) | 0 (white) | Check box
-> Initial filter (white) | 0 (white) | Check box
-> Running (white) | 0 (white) | Check box
-> Final filter (white) | 0 (white) | Check box
-> Failed (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->   Differences (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->     output different (salmon,bold) | 1 (salmon,bold) | Check box (checked)

No longer greyed out : _Approve

Changed selection in Test Tree with columns: Tests: All 1 selected, none hidden , Details
-> TargetApp (tdat.env.queuesystem) (black/white,bold) | (white)
->   Test2 (black/salmon) | output different (salmon)   ***

Current page changed in Notebook with tabs: Test , Status , Selection , Run Info
Viewing page 'Test'
...........

Showing File Tree with columns: Test2 , Details
-> Comparison Files (bold)
->   catalogue.tdat (DarkSeaGreen2) | (DarkSeaGreen2)
->   errors.tdat (DarkSeaGreen2) | (DarkSeaGreen2)
->   output.tdat (salmon) | (salmon)

------------------------------ (horizontal pane separator)
...........

========== Text Info ==========
Test FAILED on lushoto :
JOB ID:2236908
---------- Differences in output ----------
2a3
> Got environment variable /carm/proj/texttest-tmp/geoff/texttest.sge.gui.11Nov143638.108509/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/dynamic_gui.env.queuesystem.11Nov143639.108528/tdat.env.queuesystem/Test2/testdata.py
===============================

Expected application event 'completion of test actions' occurred, proceeding.

'view options for' event created with arguments 'Run Info'

Current page changed in Notebook with tabs: Test , Status , Selection , Run Info
Viewing page 'Run Info'
...........

========== Run Info ==========
Application name : TDAT
Version          : env.queuesystem
Number of tests  : 1
Executable       : /carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/TargetApp/testdata.py

Command line     : /users/geoff/.local/texttest_test/bin/texttest --vanilla site -t Test2 -v env.queuesystem -g

Start time       : 28Nov04:16:45
End time         : 28Nov04:16:46
==============================

------------------------------ (horizontal pane separator)
...........

========== Test Run Info ==========
Selected test  : Test2

Start time       : 28Nov04:16:46
End time         : 28Nov04:16:46

Description:
While this one has readable data and some environment files...

Command Line   : python /carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/TargetApp/testdata.py

Environment variables :
MY_ENV_VAR=/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/dynamic_gui.env.queuesystem.28Nov041645.4998/tdat.env.queuesystem/Test2/testdata.py
PATH=/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/dynamic_gui.env.queuesystem.28Nov041645.4998/tdat.env.queuesystem/Test2:/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/traffic_intercepts:/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv:/users/geoff/.local/texttest_test/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin
TEXTTEST_CHECKOUT=/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/
TEXTTEST_LOG_DIR=/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/dynamic_gui.env.queuesystem.28Nov041645.4998/tdat.env.queuesystem/Test2
TEXTTEST_ROOT=/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/TargetApp
TEXTTEST_SANDBOX=/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/dynamic_gui.env.queuesystem.28Nov041645.4998/tdat.env.queuesystem/Test2
TEXTTEST_SANDBOX_ROOT=/carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/dynamic_gui.env.queuesystem.28Nov041645.4998
USECASE_REPLAY_SCRIPT=

SGE Command   : qsub -N Test-Test2-TDAT.env.queuesystem -w e -notify -m n -cwd -b y -o /dev/null -e /carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/grid_core_files/slave_start_errors.ec2-user ...
Slave Command : /users/geoff/.local/texttest_test/bin/texttest -d /carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/TargetApp -a tdat.env.queuesystem -l -tp Test2 -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.4_from_28Nov100621.19144/texttest.sge.gui/TestSelf/TestData/GUI/RunInfoCopyEnv/texttesttmp/dynamic_gui.env.queuesystem.28Nov041645.4998 -servaddr 127.0.0.1:38419
===================================

'quit' event created with arguments ''
