TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/CheckoutChange based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/CheckoutChange/TargetApp/
Using SGE queues for Application HELLO, version altcheckout, checkout /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/CheckoutChange/TargetApp/../
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test succeeded on schellville
S: HELLO.altcheckout test-case Test succeeded on schellville
