TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.04Jul151953/QueueSystems/SlaveReuse/Master/ForceReuse/CheckoutChange based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application HELLO, checkout /users/geoff/texttesttmp/texttest.sge.04Jul151953/QueueSystems/SlaveReuse/Master/ForceReuse/CheckoutChange/TargetApp/
Using SGE queues for Application HELLO, version altcheckout, checkout /users/geoff/texttesttmp/texttest.sge.04Jul151953/QueueSystems/SlaveReuse/Master/ForceReuse/CheckoutChange/TargetApp/../
Q: Submitting test Test version <default> to default SGE queue
S: Test Test version <default> succeeded on schellville
S: Test Test version altcheckout succeeded on schellville
