<-SRV:TextTest slave server started on 192.168.99.27:40671
<-CMD:env 'USECASE_RECORD_STDIN=' 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic-SLEEP.killing -l "osversion=RHEL4|SOL*|HP*" -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest.py -d /users/geoff/texttesttmp/texttest.sge.08Jan172049/QueueSystems/ErrorHandling/Console/JobDeletionFails/TargetApp -a sleep -v killing -l  -tp Basic -slave /users/geoff/texttesttmp/texttest.sge.08Jan172049/QueueSystems/ErrorHandling/Console/JobDeletionFails/texttesttmp/sleep.killing.08Jan172300 -servaddr 192.168.99.27:40669 -x -xr /users/geoff/work/master/Testing/Automatic/texttest -xw /users/geoff/texttesttmp/texttest.sge.08Jan172049/QueueSystems/ErrorHandling/Console/JobDeletionFails/slave"'
->OUT:Your job 1 ("stupid") has been submitted.
<-SRV:Completed submission of all tests
->CLI:30897
sleep.killing:Basic
(idefault
Running
p1
(dp2
S'category'
p3
S'running'
p4
sS'bkgProcess'
p5
NsS'freeText'
p6
S'Running on forestville'
p7
sS'started'
p8
I1
sS'completed'
p9
I0
sS'briefText'
p10
S'RUN (forestville)'
p11
sS'executionHosts'
p12
(lp13
S'forestville'
p14
asS'lifecycleChange'
p15
S'start'
p16
sb.
<-CMD:qdel 1
->ERR:Somebody has registered the job for deletion
