<-SRV:TextTest slave server started on 10.0.2.100:34257
<-CMD:cd /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v STANDARD,DISPLAY -o /dev/null -e /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/texttesttmp/grid_core_files/slave_start_errors.fakeuser exec $SHELL -c "exec /home/matlar/work/texttest-devel/local/texttest/bin/texttest -d /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/TargetApp -a sleep.killing -l -tp Basic -slave /home/matlar/.texttest/tmp/dynamic_gui.22Jan143308.2118126/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/texttesttmp/sleep.killing.22Jan143345.2126434 -servaddr 127.0.0.1:53245 -b short_local"
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
->FIL:grid_core_files
<-CMD:qstat
<-CMD:qacct -j 1
->OUT:Some random accounting info
