<-SRV:TextTest slave server started on 10.67.7.114:45963
<-CMD:cd /nfs/vm/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/texttesttmp/grid_core_files; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -v STANDARD -o /dev/null -e /carm/proj/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/texttesttmp/grid_core_files/slave_start_errors.fakeuser exec $SHELL -c "exec /carm/proj/dave/workspace/johgil/texttest-tool/texttest/bin/texttest -d /carm/proj/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/TargetApp -a sleep.killing -l -tp Basic -slave /carm/proj/texttest-tmp-mc/johgil/dynamic_gui.29Sep135050.3187888/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/ShowSlaveStartErrors/texttesttmp/sleep.killing.29Sep135102.3201400 -servaddr 127.0.0.1:47591 -b short_local"
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
->FIL:grid_core_files
<-CMD:qstat
<-CMD:qacct -j 1
->OUT:Some random accounting info
