Using SGE queues for Application HELLO, checkout /carm/proj/texttest-tmp-mc/geoff/texttest.sge.16Dec104203.34512/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/RespectRerunLimit/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test succeeded on centreville.carmen.se
S: HELLO test-case Test FAILED on centreville.carmen.se : differences in output
Results:

Tests that did not succeed:
  HELLO test-case Test FAILED on centreville.carmen.se : differences in output

Tests Run: 2, Failures: 1
Creating batch report for application HELLO ...
done.
