Using SGE queues for Application HELLO, checkout /home/geoff/.texttest/tmp/dynamic_gui.1_from_03apr174421.64155/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/RespectRerunLimit/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Suite/Test succeeded on centreville.carmen.se
S: HELLO test-case Test FAILED on centreville.carmen.se : differences in output
Results:

Tests that did not succeed:
  HELLO test-case Test FAILED on centreville.carmen.se : differences in output

Tests Run: 2, Failures: 1
Creating batch report for application HELLO ...
done.
