Using SGE queues for Application HELLO, checkout /home/geoff/.texttest/tmp/dynamic_gui.1_from_03apr174421.64155/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/RerunTest/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Suite/Test succeeded on centreville.carmen.se
S: HELLO test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Approve(a) or continue(any other key)?
