Using SGE queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default SGE queue
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling SLEEP.killing test-case Basic in SGE (job 1)
S: SLEEP.killing test-case Basic not compared:
SGE job exited
---------- Full accounting info from SGE ----------
Your job was sent into a large mysterious void. Bad luck.

Creating batch report for application SLEEP ...
File written.
