<-SRV:TextTest slave server started on 192.168.99.111:35689
<-CMD:env 'USECASE_RECORD_STDIN=' 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' qsub -N Test-Basic-SLEEP.killing -l 'osversion=RHEL4|SOL*|HP*' -w e -notify -m n -cwd -b y -V -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest.py -d /users/geoff/texttesttmp/texttest.sgegeoff30Aug124735/QueueSystems/ErrorHandling/Console/JobSubmissionFails/TargetApp -a sleep -v killing -l  -tp Basic -slave /users/geoff/texttesttmp/texttest.sgegeoff30Aug124735/QueueSystems/ErrorHandling/Console/JobSubmissionFails/texttesttmp/sleep.killinggeoff30Aug124759 -servaddr 192.168.99.111:35687 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest -xw /users/geoff/texttesttmp/texttest.sgegeoff30Aug124735/QueueSystems/ErrorHandling/Console/JobSubmissionFails/slave"'
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
<-CMD:qdel 1
->OUT:denied: job "1" does not exist
<-CMD:qacct -j 1
->OUT:Your job was sent into a large mysterious void. Bad luck.
