<-SRV:192.168.99.64:43007
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobSubmissionFails/texttesttmp/sleep.killinggeoff28Aug101858/Basic:$PATH' 'USECASE_RECORD_SCRIPT=' 'USECASE_RECORD_STDIN=' 'USECASE_REPLAY_SCRIPT=' bsub -J Test-Basic-SLEEP.killing -u nobody -o framework_tmp/slavelog -e framework_tmp/slaveerrs 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/texttest.py -d /users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobSubmissionFails/TargetApp -a sleep -v killing -l  -tp Basic -slave /users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobSubmissionFails/texttesttmp/sleep.killinggeoff28Aug101858 -servaddr 192.168.99.64:43005 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest -xw /users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobSubmissionFails/slave"'
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobSubmissionFails/texttesttmp/sleep.killinggeoff28Aug101858/Basic:$PATH' bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.lsfgeoff28Aug101813/QueueSystems/ErrorHandling/Console/JobSubmissionFails/texttesttmp/sleep.killinggeoff28Aug101858/Basic:$PATH' bjobs -a -l 1
->OUT:Your job was sent into a large mysterious void. Bad luck.
