<-SRV:TextTest slave server started on 192.168.99.73:37833
<-CMD:cd /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobSubmissionFails/texttesttmp/sleep.killing.11Sep114054/slavelogs; env 'USECASE_RECORD_SCRIPT=' 'USECASE_REPLAY_SCRIPT=' bsub -J Test-Basic-SLEEP.killing -u nobody -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors 'exec /bin/tcsh -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest -d /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobSubmissionFails/TargetApp -a sleep -v killing -l -tp Basic -slave /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobSubmissionFails/texttesttmp/sleep.killing.11Sep114054 -servaddr 192.168.99.73:37825 -b short_local -x -xr /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest -xw /users/geoff/texttesttmp/texttest.11Sep114032/texttest.lsf/QueueSystems/ErrorHandling/Console/JobSubmissionFails/slave"'
->OUT:Job <1> is submitted to queue <bad_machine_queue>.
<-SRV:Completed submission of all tests
<-CMD:bkill -s USR1 1
->ERR:Job <1>: No matching job found
<-CMD:bjobs -a -l 1
->OUT:Your job was sent into a large mysterious void. Bad luck.
