Using SGE queues for Application HELLO, checkout /tmp/geoff/texttest.25May170933.41187/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ResubmitTest/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test succeeded on centreville.carmen.se
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Approve(a) or continue(any other key)?
