TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.13Jun125326/QueueSystems/Performance/Miscellaneous/ForcePerfResource based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application PERF, version resource
Q: Submitting test Failures to default SGE queue
S: Test Failures FAILED on perf_machine1 : new results in logperf
View details(v), Save Version resource(1), Save(s) or continue(any other key)?
