TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.lsf/QueueSystems/Performance/Miscellaneous/ForcePerfResource based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application PERF, version resource
Q: Submitting PERF.resource test-case Failures to default LSF queue
S: PERF.resource test-case Failures FAILED on perf_machine1 : new results in logperf
View details(v), Save Version resource(1), Save(s) or continue(any other key)?
