TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Performance/Miscellaneous/ForcePerfResource based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/Performance/Miscellaneous/ForcePerfResource/logging
Using SGE queues for Application PERF, version resource
Q: Submitting PERF.resource test-case Failures to default SGE queue
S: PERF.resource test-case Failures FAILED on perf_machine1 : new results in logperf
View details(v), Save Version resource(1), Save(s) or continue(any other key)?
