TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.30Nov175319/QueueSystems/Performance/Miscellaneous/ForcePerfResource based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application PERF, version resource
Submitting PERF test-suite TargetApp to SGE queues
  Submitting PERF test-case Failures to default SGE queue
  PERF test-case Failures FAILED on perf_machine1 : new results in logperf
  View details(v), Save Version resource(1), Save(s) or continue(any other key)?
