TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff18Aug175212/QueueSystems/Performance/Miscellaneous/ForcePerfResource based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application PERF, version resource
Submitting PERF test-suite TargetApp to LSF queues
  Submitting PERF test-case Failures to default LSF queue
  Evaluating PERF test-case Failures (on errors.perf,logperf.perf,output.perf)
  PERF test-case Failures FAILED on forestville : new results in logperf
  View details(v), Save Version resource(1), Save(s) or continue(any other key)?
