<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.sgegeoff28Aug101813/QueueSystems/Performance/Miscellaneous/ReportOtherJobs/texttesttmp/perf.resourcegeoff28Aug101851/Failures:$PATH' 'USECASE_RECORD_SCRIPT=/users/geoff/texttesttmp/texttest.sgegeoff28Aug101813/QueueSystems/Performance/Miscellaneous/ReportOtherJobs/texttesttmp/perf.resourcegeoff28Aug101851/Failures/usecase.perf' 'USECASE_RECORD_STDIN=/users/geoff/texttesttmp/texttest.sgegeoff28Aug101813/QueueSystems/Performance/Miscellaneous/ReportOtherJobs/texttesttmp/perf.resourcegeoff28Aug101851/Failures/input.perf' qselect -l performance_resource
->OUT:idle@perf_machine1.carmen.se
idle@perf_machine2.carmen.se
idle@bagotville.carmen.se
idle@batesville.carmen.se
idle@bellville.carmen.se
login@perf_machine1.carmen.se
login@perf_machine2.carmen.se
login@bagotville.carmen.se
login@batesville.carmen.se
login@bellville.carmen.se
waiting@perf_machine1.carmen.se
waiting@perf_machine2.carmen.se
waiting@bagotville.carmen.se
waiting@batesville.carmen.se
waiting@bellville.carmen.se
build@perf_machine1.carmen.se
build@perf_machine2.carmen.se
build@bagotville.carmen.se
build@batesville.carmen.se
build@bellville.carmen.se
short@perf_machine1.carmen.se
short@perf_machine2.carmen.se
short@bagotville.carmen.se
short@batesville.carmen.se
short@bellville.carmen.se
normal@perf_machine1.carmen.se
normal@perf_machine2.carmen.se
normal@bagotville.carmen.se
normal@batesville.carmen.se
normal@bellville.carmen.se
<-CMD:env 'PATH=/users/geoff/texttesttmp/texttest.sgegeoff28Aug101813/QueueSystems/Performance/Miscellaneous/ReportOtherJobs/texttesttmp/perf.resourcegeoff28Aug101851/Failures:$PATH' 'USECASE_RECORD_SCRIPT=/users/geoff/texttesttmp/texttest.sgegeoff28Aug101813/QueueSystems/Performance/Miscellaneous/ReportOtherJobs/texttesttmp/perf.resourcegeoff28Aug101851/Failures/usecase.perf' 'USECASE_RECORD_STDIN=/users/geoff/texttesttmp/texttest.sgegeoff28Aug101813/QueueSystems/Performance/Miscellaneous/ReportOtherJobs/texttesttmp/perf.resourcegeoff28Aug101851/Failures/input.perf' qstat -r -s r -l hostname=perf_machine1
->OUT:job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------
4849948 0.50000 a_very_long_ johnny         r     08/17/2006 20:05:46 normal@perf_machine1.carmen.se            1        
       Full jobname:     a_very_long_job_name
       Master queue:     normal@perf_machine1.carmen.se
       Hard Resources:   carmarch=*linux* (0.000000)
                         carmrun12=TRUE (0.000000)
       Soft Resources:   
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------
4849949 0.50000 another_very mary           r     08/17/2006 20:05:46 normal@perf_machine1.carmen.se            1        
       Full jobname:     another_very_long_job_name
       Master queue:     normal@perf_machine1.carmen.se
       Hard Resources:   carmarch=*linux* (0.000000)
                         carmrun12=TRUE (0.000000)
       Soft Resources:   
