TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/BadResource based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version badresource, checkout /users/geoff/texttesttmp/texttest.sgegeoff23Feb173426/QueueSystems/Console/BadResource/TargetApp
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic  to default SGE queue
  SLEEP test-case Basic  not compared:  Failed to submit to SGE (Unable to run job: unknown resource "no_such_resource".)
  Submitting SLEEP test-case Basic2 to default SGE queue
  SLEEP test-case Basic2 not compared:  Failed to submit to SGE (Unable to run job: unknown resource "no_such_resource".)
