TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff10Jul112103/QueueSystems/GUI/QuitDuringSetup based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application HELLO
Submitting HELLO test-suite TargetApp to LSF queues
  Submitting HELLO test-suite Suite1 to LSF queues
    Submitting HELLO test-case Test1 to default LSF queue
Terminating testing due to external interruption (Interrupted externally)
    Cancelling HELLO test-case Test1 in LSF (job 1)
