TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsfgeoff29Mar145806/TestSelf/EnvironmentFile/RemoveSuiteVars based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application Env Variables, version lsf, checkout /nfs/vm/texttest/central_texttesttmp/texttest.lsfgeoff29Mar145806/TestSelf/EnvironmentFile/RemoveSuiteVars/TargetApp/./
Submitting Env Variables test-suite TargetApp to LSF queues
  Submitting Env Variables test-suite Suite1 to LSF queues
    Submitting Env Variables test-case Test1 to default LSF queue
  Submitting Env Variables test-case Test2  to default LSF queue
    Evaluating Env Variables test-case Test1 - SUCCESS! (on output.env)
  Evaluating Env Variables test-case Test2  - SUCCESS! (on output.env)
