TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.13Jun125151/TestSelf/EnvironmentFile/Console/RemoveSuiteVars based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application Env Variables, version lsf
Q: Submitting test Test1 to default SGE queue
Q: Submitting test Test2 to default SGE queue
S: Test Test2 FAILED on hendersonville : missing results for errors
View details(v), Save Version lsf(1), Save(s) or continue(any other key)?
S: Test Test1 FAILED on graceville : missing results for errors
View details(v), Save Version lsf(1), Save(s) or continue(any other key)?
