TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.05Dec114258/QueueSystems/NormalOperation/GUI/ViewRunning based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing2
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Terminating testing due to external interruption (Interrupted externally)
  Cancelling SLEEP test-case Basic in SGE (job 6662503)
