TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.lsf/QueueSystems/NormalOperation/GUI/ViewRunning based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application SLEEP, version killing2
Q: Submitting SLEEP.killing2 test-case Basic to default LSF queue
T: Cancelling SLEEP.killing2 test-case Basic in LSF (job 471297)
