TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sge.29May152637/QueueSystems/NormalOperation/GUI/ViewRunning based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using Application SLEEP, version killing2
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
  Cancelling SLEEP test-case Basic in SGE (job 6662741)
