TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.05Dec114841/QueueSystems/NormalOperation/GUI/ViewRunning based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing2
Submitting SLEEP test-suite TargetApp to LSF queues
  Submitting SLEEP test-case Basic to default LSF queue
Terminating testing due to external interruption (Interrupted externally)
  Cancelling SLEEP test-case Basic in LSF (job 471297)
