TextTest will write diagnostics in /nfs/vm/texttest-tmp/geoff/texttest.25Jan105649/texttest.sge/QueueSystems/NormalOperation/GUI/ViewRunning based on file at /carm/proj/texttest-tmp/geoff/texttest.25Jan105649/texttest.sge/QueueSystems/NormalOperation/GUI/ViewRunning/logging
Using SGE queues for Application SLEEP, version killing2
Q: Submitting SLEEP.killing2 test-case Basic to default SGE queue
T: Cancelling SLEEP.killing2 test-case Basic in SGE (job 6662741)
