TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/NormalOperation/GUI/ViewRunning based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.lsf/QueueSystems/NormalOperation/GUI/ViewRunning/logging
Using LSF queues for Application SLEEP, version killing2
Q: Submitting SLEEP.killing2 test-case Basic to default LSF queue
T: Cancelling SLEEP.killing2 test-case Basic in LSF (job 471297)
