#!/usr/bin/env python
import sys, string, os

def machineStr():
    if os.environ.has_key("TEXTTEST_FAKE_MACHINE"):
        return "fake machine " + os.getenv("TEXTTEST_FAKE_MACHINE")
    else:
        return "local host"

args = string.join(sys.argv[1:])
progName = os.path.basename(sys.argv[0])
sys.stderr.write("I'm a fake " + progName + " with arguments '" + args + "' on " + machineStr() + "\n")
