TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/DuplicateSlave based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using SGE queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default SGE queue
Q: Submitting SLEEP test-case Basic2 to default SGE queue
S: SLEEP test-case Basic2 FAILED on connellsville : new results in errors,output
S: SLEEP test-case Basic succeeded on graceville
At 17:34 creating batch report for application SLEEP ...file written.
