TextTest will write diagnostics in /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/DuplicateSlave based on file at /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/DuplicateSlave/logging
Using SGE queues for Application SLEEP
Q: Submitting SLEEP test-case Basic to default SGE queue
Q: Submitting SLEEP test-case Basic2 to default SGE queue
S: SLEEP test-case Basic2 FAILED on connellsville : new results in errors,output
S: SLEEP test-case Basic succeeded on graceville
At 15:40 creating batch report for application SLEEP ...file written.
